import type { OpsAction, OpsEntity, OpsField } from "./ops.spec.js";

export type MoreEntityKey =
  | "applications"
  | "appDocuments"
  | "interviews"
  | "offers"
  | "intakes"
  | "changeRequests"
  | "complianceCases"
  | "retention"
  | "legalHolds"
  | "privacyRequests"
  | "evidence"
  | "recordVault"
  | "disposals"
  | "submissions"
  | "ruleSets"
  | "approvals"
  | "workflowDefs"
  | "aiInteractions"
  | "knowledge"
  | "sessions"
  | "auditLog"
  | "outbox"
  | "notifications"
  | "helpdesk";

const f = (key: string, label: string, kind: OpsField["kind"], extra: Partial<OpsField> = {}): OpsField => ({ key, label, kind, ...extra });
const sel = (key: string, label: string, options: string[], extra: Partial<OpsField> = {}): OpsField => ({ key, label, kind: "select", options, required: true, dflt: options[0], ...extra });
const ro = (key: string, label: string, kind: OpsField["kind"] = "text"): OpsField => ({ key, label, kind, readOnly: true });
const act = (key: string, label: string, set: OpsAction["set"], when: OpsAction["when"], tone?: OpsAction["tone"]): OpsAction => ({ key, label, set, when, ...(tone ? { tone } : {}) });

/** Applicant lifecycle; the first block are the Heritage SIS lead statuses already stored on older applications. */
export const APP_STAGES = ["new_inquiry", "prospective", "follow_up", "draft", "submitted", "under_review", "interview", "waitlisted", "approved_application", "offered", "cloa", "accepted", "enrolled", "declined", "refused_visa", "withdrawn"];
export const APP_EARLY = ["new_inquiry", "prospective", "follow_up", "draft", "submitted", "under_review"];
export const APP_ADMITTED = ["approved_application", "offered", "cloa", "accepted", "enrolled"];
export const OFFER_TITLES = ["Conditional Offer", "Unconditional Offer", "Letter of Acceptance (LOA)", "Conditional LOA (CLOA)"];
export const APPROVAL_TYPES = ["grade_publish", "grade.publish", "leave_of_absence", "student_profile_change", "service_request.course_withdrawal", "service_request.academic_appeal", "course_session_new", "course_session_change"];
export const RULE_FACTS = ["Academic standing", "Program", "Active enrolments", "Open success cases", "Approved transfer credits", "Placement hours (approved)"];
export const RULE_OPS = ["equals", "does not equal", "contains", "is greater than", "is less than"];

export const MORE_ENTITIES: Record<MoreEntityKey, OpsEntity> = {
  /* ---------------------------- Admissions ---------------------------- */
  applications: {
    module: "admissions",
    label: "Application",
    plural: "Applications",
    store: "table",
    screen: "OPS:AD_APPLICATION",
    fields: [
      f("givenName", "First Name", "text", { required: true }),
      f("familyName", "Last Name", "text", { required: true }),
      f("email", "E-mail", "email", { required: true, hint: "An applicant portal account is created for new e-mail addresses (they set a password with “Forgot password”)." }),
      f("phone", "Phone", "text"),
      f("programName", "Program", "ref", { ref: "programs", byLabel: true, required: true }),
      f("intakeTerm", "Intake Term", "ref", { ref: "terms", byLabel: true, required: true }),
      sel("status", "Stage", APP_STAGES, { dflt: "submitted" }),
      f("progressPct", "Progress %", "number", { integer: true, min: 0, max: 100, dflt: 50 }),
      f("notes", "Internal Notes", "textarea"),
      ro("submittedAt", "Submitted", "datetime"),
      ro("_student", "Student Record"),
    ],
    columns: [
      { key: "_name", label: "Applicant" },
      { key: "email", label: "E-mail" },
      { key: "programName", label: "Program" },
      { key: "intakeTerm", label: "Intake" },
      { key: "_docs", label: "Documents" },
      { key: "progressPct", label: "%" },
      { key: "status", label: "Stage" },
    ],
    filters: ["status", "programName", "intakeTerm"],
    actions: [
      act("review", "Start Review", { status: "under_review" }, { status: ["new_inquiry", "prospective", "follow_up", "draft", "submitted"] }, "primary"),
      act("admit", "Admit", { status: "approved_application" }, { status: ["submitted", "under_review", "interview", "waitlisted"] }, "primary"),
      act("waitlist", "Waitlist", { status: "waitlisted" }, { status: ["under_review", "interview"] }),
      { key: "convert", label: "Convert to Student", run: true, when: { status: ["accepted", "cloa"], _converted: [false] }, tone: "primary" },
      act("decline", "Decline", { status: "declined" }, { status: [...APP_EARLY, "interview", "waitlisted", "approved_application"] }, "danger"),
      act("visa", "Visa Refused", { status: "refused_visa" }, { status: ["approved_application", "offered", "cloa", "accepted"] }, "danger"),
    ],
    hint: "Stage changes are added to the applicant's timeline and sent to their portal notifications. Admitting checks the intake capacity.",
  },
  appDocuments: {
    module: "admissions",
    label: "Document",
    plural: "Document Review",
    store: "table",
    screen: "OPS:AD_DOCUMENT",
    fields: [
      f("applicationId", "Application", "ref", { ref: "applications", required: true }),
      f("label", "Document", "text", { required: true }),
      sel("status", "Status", ["missing", "uploaded", "accepted", "rejected"]),
      ro("fileName", "Uploaded File"),
    ],
    columns: [
      { key: "applicationId", label: "Application" },
      { key: "label", label: "Document" },
      { key: "fileName", label: "File" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("accept", "Accept", { status: "accepted" }, { status: ["uploaded"] }, "primary"),
      act("reject", "Reject", { status: "rejected" }, { status: ["uploaded"] }, "danger"),
      act("request", "Request Again", { status: "missing" }, { status: ["rejected"] }),
    ],
    hint: "Applicants upload files from the applicant portal; adding a document here asks them for it.",
  },
  interviews: {
    module: "admissions",
    label: "Interview",
    plural: "Interviews",
    store: "record",
    screen: "OPS:AD_INTERVIEW",
    fields: [
      f("applicationId", "Application", "ref", { ref: "applications", required: true }),
      f("interviewerId", "Interviewer", "ref", { ref: "staff", required: true }),
      f("scheduledAt", "Date & Time", "datetime", { required: true }),
      sel("mode", "Mode", ["Video", "In person", "Phone"]),
      f("location", "Room / Meeting Link", "text"),
      sel("status", "Status", ["Scheduled", "Completed", "No-show", "Cancelled"]),
      f("score", "Score (1–5)", "number", { integer: true, min: 1, max: 5 }),
      f("recommendation", "Recommendation", "select", { options: ["Admit", "Waitlist", "Decline"] }),
      f("notes", "Interview Notes", "textarea"),
    ],
    columns: [
      { key: "scheduledAt", label: "When" },
      { key: "applicationId", label: "Applicant" },
      { key: "interviewerId", label: "Interviewer" },
      { key: "mode", label: "Mode" },
      { key: "score", label: "Score" },
      { key: "recommendation", label: "Recommendation" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "recommendation", "mode"],
    actions: [
      act("complete", "Complete", { status: "Completed" }, { status: ["Scheduled"] }, "primary"),
      act("noshow", "No-show", { status: "No-show" }, { status: ["Scheduled"] }),
      act("cancel", "Cancel", { status: "Cancelled" }, { status: ["Scheduled"] }, "danger"),
    ],
    hint: "Scheduling moves the application to the Interview stage. A completed interview needs a score and recommendation.",
  },
  offers: {
    module: "admissions",
    label: "Offer / LOA",
    plural: "Offers & LOAs",
    store: "table",
    screen: "OPS:AD_OFFER",
    fields: [
      f("applicationId", "Application", "ref", { ref: "applications", required: true }),
      sel("title", "Letter Type", OFFER_TITLES),
      f("conditions", "Conditions / Letter Body", "textarea"),
      f("expiresOn", "Respond By", "date"),
      sel("status", "Status", ["draft", "pending", "accepted", "declined", "withdrawn"]),
    ],
    columns: [
      { key: "applicationId", label: "Applicant" },
      { key: "title", label: "Letter" },
      { key: "expiresOn", label: "Respond By" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "title"],
    actions: [
      act("issue", "Issue to Applicant", { status: "pending" }, { status: ["draft"] }, "primary"),
      act("accept", "Record Acceptance", { status: "accepted" }, { status: ["pending"] }),
      act("decline", "Record Decline", { status: "declined" }, { status: ["pending"] }),
      act("withdraw", "Withdraw", { status: "withdrawn" }, { status: ["draft", "pending"] }, "danger"),
    ],
    hint: "Drafts are invisible to the applicant. Issued letters appear in the applicant portal, where the applicant accepts or declines.",
  },
  intakes: {
    module: "admissions",
    label: "Intake",
    plural: "Intake Capacity",
    store: "record",
    screen: "OPS:AD_INTAKE",
    fields: [
      f("programName", "Program", "ref", { ref: "programs", byLabel: true, required: true }),
      f("intakeTerm", "Intake Term", "ref", { ref: "terms", byLabel: true, required: true }),
      f("capacity", "Seats", "number", { integer: true, min: 1, max: 10000, required: true }),
      sel("status", "Status", ["Open", "Waitlist only", "Closed"]),
      f("notes", "Notes", "textarea"),
    ],
    columns: [
      { key: "programName", label: "Program" },
      { key: "intakeTerm", label: "Intake" },
      { key: "capacity", label: "Seats" },
      { key: "_applied", label: "Applied" },
      { key: "_admitted", label: "Admitted" },
      { key: "_remaining", label: "Remaining" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("waitlist", "Waitlist Only", { status: "Waitlist only" }, { status: ["Open"] }),
      act("close", "Close", { status: "Closed" }, { status: ["Open", "Waitlist only"] }, "danger"),
      act("open", "Reopen", { status: "Open" }, { status: ["Waitlist only", "Closed"] }, "primary"),
    ],
    hint: "Applied and admitted counts are live from Applications with the same program and intake term.",
  },

  /* ---------------------------- Academics ----------------------------- */
  changeRequests: {
    module: "academics",
    label: "Change Request",
    plural: "Program Change Requests",
    store: "record",
    screen: "OPS:AC_CHANGE",
    fields: [
      f("programId", "Program", "ref", { ref: "programs", required: true }),
      sel("type", "Change Type", ["Add course", "Remove course", "Credit change", "Requirement change", "Program name / description", "Delivery change", "Other"]),
      f("title", "Summary", "text", { required: true }),
      f("rationale", "Rationale", "textarea", { required: true }),
      f("effectiveTerm", "Effective Term", "ref", { ref: "terms", byLabel: true }),
      f("requestedBy", "Requested By", "ref", { ref: "staff" }),
      sel("status", "Status", ["Draft", "Submitted", "Approved", "Rejected", "Implemented"]),
      f("decisionNote", "Decision Note", "textarea"),
    ],
    columns: [
      { key: "title", label: "Request" },
      { key: "programId", label: "Program" },
      { key: "type", label: "Type" },
      { key: "effectiveTerm", label: "Effective" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "type"],
    actions: [
      act("submit", "Submit", { status: "Submitted" }, { status: ["Draft"] }, "primary"),
      act("approve", "Approve", { status: "Approved" }, { status: ["Submitted"] }, "primary"),
      act("reject", "Reject", { status: "Rejected" }, { status: ["Submitted"] }, "danger"),
      act("implement", "Mark Implemented", { status: "Implemented" }, { status: ["Approved"] }),
      act("reopen", "Reopen as Draft", { status: "Draft" }, { status: ["Rejected"] }),
    ],
    hint: "Rejecting requires a decision note. Approved changes are applied in Program Management, then marked implemented here.",
  },

  /* ---------------------------- Compliance ---------------------------- */
  complianceCases: {
    module: "compliance",
    label: "Compliance Case",
    plural: "Compliance Cases",
    store: "table",
    screen: "OPS:CP_CASE",
    fields: [
      ro("title", "Case"),
      ro("caseKind", "Kind"),
      ro("_subject", "Subject"),
      ro("missCount", "Misses", "number"),
      ro("detail", "Detail", "textarea"),
      sel("severity", "Severity", ["info", "warning", "critical"]),
      sel("status", "Status", ["open", "resolved", "dismissed"]),
      f("explanation", "Resolution Note", "textarea"),
      ro("resolvedAt", "Resolved", "datetime"),
    ],
    columns: [
      { key: "title", label: "Case" },
      { key: "caseKind", label: "Kind" },
      { key: "_subject", label: "Subject" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "severity"],
    actions: [
      act("resolve", "Resolve", { status: "resolved" }, { status: ["open"] }, "primary"),
      act("dismiss", "Dismiss", { status: "dismissed" }, { status: ["open"] }),
      act("reopen", "Reopen", { status: "open" }, { status: ["resolved", "dismissed"] }),
    ],
    create: false,
    remove: false,
    hint: "Cases are raised automatically by the campus compliance sweep (attendance and live-session participation).",
  },
  retention: {
    module: "compliance",
    label: "Retention Policy",
    plural: "Retention Policies",
    store: "record",
    screen: "OPS:CP_RETENTION",
    fields: [
      sel("recordType", "Record Type", ["Student file", "Academic transcript", "Admissions application", "Financial record", "Attendance record", "Placement record", "Lab incident", "Audit log", "Correspondence"]),
      f("years", "Keep For (years)", "number", { integer: true, min: 1, max: 100, required: true }),
      sel("trigger", "Counted From", ["Graduation or withdrawal", "Last activity", "Record creation"]),
      sel("disposal", "Then", ["Destroy", "Anonymize", "Archive"]),
      f("authority", "Legal Basis", "text"),
      sel("status", "Status", ["Active", "Draft", "Retired"]),
    ],
    columns: [
      { key: "recordType", label: "Record Type" },
      { key: "years", label: "Years" },
      { key: "trigger", label: "Counted From" },
      { key: "disposal", label: "Then" },
      { key: "_disposals", label: "Disposals" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "disposal"],
    actions: [act("activate", "Activate", { status: "Active" }, { status: ["Draft", "Retired"] }, "primary"), act("retire", "Retire", { status: "Retired" }, { status: ["Active"] })],
  },
  legalHolds: {
    module: "compliance",
    label: "Legal Hold",
    plural: "Legal Holds",
    store: "record",
    screen: "OPS:CP_HOLD",
    fields: [
      f("matter", "Matter", "text", { required: true }),
      f("studentId", "Student", "ref", { ref: "students", required: true }),
      f("scope", "Records Covered", "text", { hint: "e.g. Full student file, Finance records" }),
      f("custodianId", "Custodian", "ref", { ref: "staff" }),
      f("placedOn", "Placed On", "date", { required: true, dflt: "$today" }),
      f("releasedOn", "Released On", "date"),
      sel("status", "Status", ["Active", "Released"]),
      f("reason", "Reason", "textarea"),
    ],
    columns: [
      { key: "matter", label: "Matter" },
      { key: "studentId", label: "Student" },
      { key: "custodianId", label: "Custodian" },
      { key: "placedOn", label: "Placed" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [act("release", "Release", { status: "Released", releasedOn: "$today" }, { status: ["Active"] }, "primary")],
    hint: "Students under an active hold cannot have records disposed of or deletion requests fulfilled.",
  },
  privacyRequests: {
    module: "compliance",
    label: "Privacy Request",
    plural: "Privacy Requests",
    store: "record",
    screen: "OPS:CP_PRIVACY",
    fields: [
      f("studentId", "Requester (Student)", "ref", { ref: "students", required: true }),
      sel("type", "Request", ["Access", "Correction", "Deletion", "Restriction", "Portability"]),
      f("receivedOn", "Received", "date", { required: true, dflt: "$today" }),
      f("dueOn", "Due", "date", { hint: "Defaults to 30 days after it was received." }),
      f("handlerId", "Handled By", "ref", { ref: "staff" }),
      sel("status", "Status", ["Received", "In Progress", "Fulfilled", "Refused"]),
      f("closedOn", "Closed On", "date"),
      f("response", "Response", "textarea"),
    ],
    columns: [
      { key: "receivedOn", label: "Received" },
      { key: "studentId", label: "Requester" },
      { key: "type", label: "Request" },
      { key: "dueOn", label: "Due" },
      { key: "_due", label: "Deadline" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "type"],
    actions: [
      act("start", "Start", { status: "In Progress" }, { status: ["Received"] }, "primary"),
      act("fulfil", "Fulfil", { status: "Fulfilled", closedOn: "$today" }, { status: ["Received", "In Progress"] }, "primary"),
      act("refuse", "Refuse", { status: "Refused", closedOn: "$today" }, { status: ["Received", "In Progress"] }, "danger"),
    ],
    hint: "Refusing needs a written response. Deletion requests cannot be fulfilled while the student is under a legal hold.",
  },
  evidence: {
    module: "compliance",
    label: "Evidence Item",
    plural: "Accreditation Evidence",
    store: "record",
    screen: "OPS:CP_EVIDENCE",
    fields: [
      f("standard", "Standard / Criterion", "text", { required: true, hint: "e.g. PTIB 4.2 – Student records" }),
      f("title", "Evidence", "text", { required: true }),
      f("programId", "Program", "ref", { ref: "programs" }),
      f("ownerId", "Owner", "ref", { ref: "staff" }),
      f("url", "Document Link", "url"),
      f("dueOn", "Due", "date"),
      sel("status", "Status", ["Needed", "In Review", "Accepted"]),
      f("notes", "Notes", "textarea"),
    ],
    columns: [
      { key: "standard", label: "Standard" },
      { key: "title", label: "Evidence" },
      { key: "ownerId", label: "Owner" },
      { key: "dueOn", label: "Due" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("submit", "Submit for Review", { status: "In Review" }, { status: ["Needed"] }, "primary"),
      act("accept", "Accept", { status: "Accepted" }, { status: ["In Review"] }, "primary"),
      act("return", "Return", { status: "Needed" }, { status: ["In Review"] }),
    ],
    hint: "Submitting requires a document link.",
  },
  recordVault: {
    module: "compliance",
    label: "Record",
    plural: "Record Vault",
    store: "table",
    screen: "OPS:CP_VAULT",
    fields: [
      f("studentId", "Student", "ref", { ref: "students", required: true }),
      f("recordName", "Record", "text", { required: true }),
      f("docLabel", "Document Label", "text"),
      f("recordDate", "Record Date", "date"),
      f("downloadUrl", "File Link", "text"),
      sel("status", "Status", ["available", "restricted", "archived"]),
      f("note", "Note", "textarea"),
    ],
    columns: [
      { key: "studentId", label: "Student" },
      { key: "recordName", label: "Record" },
      { key: "docLabel", label: "Label" },
      { key: "recordDate", label: "Date" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("restrict", "Restrict", { status: "restricted" }, { status: ["available"] }),
      act("archive", "Archive", { status: "archived" }, { status: ["available", "restricted"] }),
      act("restore", "Restore", { status: "available" }, { status: ["restricted", "archived"] }, "primary"),
    ],
    hint: "These are the documents students see under Documents in their portal. Restricted and archived records stay on file.",
  },
  disposals: {
    module: "compliance",
    label: "Disposal",
    plural: "Disposal Review",
    store: "record",
    screen: "OPS:CP_DISPOSAL",
    fields: [
      f("policyId", "Retention Policy", "ref", { ref: "retentionPolicies", required: true }),
      f("studentId", "Student", "ref", { ref: "students", required: true }),
      f("records", "Records", "text", { required: true }),
      f("eligibleOn", "Eligible On", "date", { required: true }),
      sel("status", "Status", ["Proposed", "Approved", "Disposed", "Rejected"]),
      f("disposedOn", "Disposed On", "date"),
      f("notes", "Notes", "textarea"),
    ],
    columns: [
      { key: "studentId", label: "Student" },
      { key: "records", label: "Records" },
      { key: "policyId", label: "Policy" },
      { key: "eligibleOn", label: "Eligible" },
      { key: "_hold", label: "Legal Hold" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("approve", "Approve", { status: "Approved" }, { status: ["Proposed"] }, "primary"),
      act("dispose", "Mark Disposed", { status: "Disposed", disposedOn: "$today" }, { status: ["Approved"] }, "danger"),
      act("reject", "Reject", { status: "Rejected" }, { status: ["Proposed", "Approved"] }),
    ],
    hint: "Approval is blocked while the student has an active legal hold or before the eligible date.",
  },

  /* ------------------------------- Forms ------------------------------ */
  submissions: {
    module: "forms",
    label: "Submission",
    plural: "Form Submissions",
    store: "record",
    screen: "OPS:FM_SUBMISSION",
    fields: [
      f("formId", "Form", "ref", { ref: "forms", required: true }),
      f("studentId", "Submitted By", "ref", { ref: "students", required: true }),
      f("submittedOn", "Submitted On", "date", { required: true, dflt: "$today" }),
      f("answers", "Answers", "textarea", { required: true, hint: "One answer per line, e.g. “Emergency contact: Jane Doe”." }),
      sel("status", "Status", ["Submitted", "Under Review", "Approved", "Rejected"]),
      f("reviewerId", "Reviewer", "ref", { ref: "staff" }),
      f("reviewNote", "Review Note", "textarea"),
    ],
    columns: [
      { key: "submittedOn", label: "Submitted" },
      { key: "formId", label: "Form" },
      { key: "studentId", label: "Submitted By" },
      { key: "reviewerId", label: "Reviewer" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [
      act("review", "Start Review", { status: "Under Review" }, { status: ["Submitted"] }, "primary"),
      act("approve", "Approve", { status: "Approved" }, { status: ["Submitted", "Under Review"] }, "primary"),
      act("reject", "Reject", { status: "Rejected" }, { status: ["Submitted", "Under Review"] }, "danger"),
    ],
    hint: "Forms are designed in System Configuration → Form Management. Required form fields must appear in the answers; the student is notified of the decision.",
  },

  /* ------------------------------- Rules ------------------------------ */
  ruleSets: {
    module: "rules",
    label: "Rule",
    plural: "Rules",
    store: "record",
    screen: "OPS:RL_RULE",
    fields: [
      f("name", "Rule Name", "text", { required: true }),
      sel("fact", "When Student's", RULE_FACTS),
      sel("operator", "Operator", RULE_OPS),
      f("value", "Value", "text", { required: true, hint: "Numbers for counts and hours; text for standing and program." }),
      sel("outcome", "Then", ["Flag only", "Open success case"]),
      f("caseLevel", "Case Level", "select", { options: ["watch", "warning", "alert", "critical"], dflt: "warning" }),
      sel("status", "Status", ["Draft", "Active", "Paused"]),
      f("description", "Description", "textarea"),
      ro("_sample", "Currently Matching (sample)", "textarea"),
      ro("_lastRun", "Last Run"),
    ],
    columns: [
      { key: "name", label: "Rule" },
      { key: "_condition", label: "Condition" },
      { key: "outcome", label: "Then" },
      { key: "_matches", label: "Matching Now" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "outcome"],
    actions: [
      act("activate", "Activate", { status: "Active" }, { status: ["Draft", "Paused"] }, "primary"),
      act("pause", "Pause", { status: "Paused" }, { status: ["Active"] }),
      { key: "run", label: "Run Now", run: true, when: { status: ["Active"] }, tone: "primary" },
    ],
    hint: "Matching counts are evaluated live against student records. Running an active “Open success case” rule opens a case for each matching student who has no open case.",
  },

  /* ----------------------------- Workflows ---------------------------- */
  approvals: {
    module: "workflows",
    label: "Request",
    plural: "Approval Requests",
    store: "table",
    screen: "OPS:WF_REQUEST",
    fields: [
      ro("type", "Type"),
      ro("_subject", "Subject"),
      ro("_requester", "Requested By"),
      ro("createdAt", "Requested", "datetime"),
      ro("status", "Status"),
      ro("_decisions", "Decisions", "textarea"),
      ro("_diff", "Proposed Change", "textarea"),
      ro("_where", "Decided In"),
    ],
    columns: [
      { key: "createdAt", label: "Requested" },
      { key: "type", label: "Type" },
      { key: "_subject", label: "Subject" },
      { key: "_requester", label: "Requested By" },
      { key: "_age", label: "Age" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "type"],
    actions: [
      { key: "approve", label: "Approve", run: true, when: { status: ["pending"], _inbox: [true] }, tone: "primary" },
      { key: "reject", label: "Reject", run: true, when: { status: ["pending"], _inbox: [true] }, tone: "danger" },
      { key: "apply", label: "Apply", run: true, when: { status: ["approved"], _inbox: [true] }, tone: "primary" },
    ],
    create: false,
    edit: false,
    remove: false,
    hint: "Approving applies the change immediately (grade publishing, profile changes, leave of absence, service requests). Course schedule requests are decided in My Courses → Pending Course Schedules.",
  },
  workflowDefs: {
    module: "workflows",
    label: "Workflow",
    plural: "Workflow Definitions",
    store: "record",
    screen: "OPS:WF_DEF",
    fields: [
      f("name", "Workflow Name", "text", { required: true }),
      sel("requestType", "Request Type", APPROVAL_TYPES),
      f("approverRoles", "Approver Roles", "list", { required: true, dflt: ["admin", "registrar"] }),
      f("slaHours", "Decision SLA (hours)", "number", { integer: true, min: 1, max: 2000, required: true, dflt: 48 }),
      sel("status", "Status", ["Active", "Inactive"]),
      f("description", "Description", "textarea"),
    ],
    columns: [
      { key: "name", label: "Workflow" },
      { key: "requestType", label: "Request Type" },
      { key: "slaHours", label: "SLA (h)" },
      { key: "_pending", label: "Pending" },
      { key: "_breaches", label: "Over SLA" },
      { key: "_avg", label: "Avg Decision" },
      { key: "status", label: "Status" },
    ],
    filters: ["status"],
    actions: [act("deactivate", "Deactivate", { status: "Inactive" }, { status: ["Active"] }), act("activate", "Activate", { status: "Active" }, { status: ["Inactive"] }, "primary")],
    hint: "Pending, over-SLA and average decision time are measured live from approval requests of the same type.",
  },

  /* -------------------------------- AI -------------------------------- */
  aiInteractions: {
    module: "ai",
    label: "Interaction",
    plural: "Interactions",
    store: "table",
    screen: "OPS:AI_INTERACTION",
    fields: [
      ro("createdAt", "When", "datetime"),
      ro("_user", "User"),
      ro("role", "Portal"),
      ro("capability", "Capability"),
      ro("provider", "Provider"),
      ro("question", "Question", "textarea"),
      ro("answer", "Answer", "textarea"),
      ro("_sources", "Sources Cited", "textarea"),
      ro("estimatedTokens", "Tokens", "number"),
      ro("latencyMs", "Latency (ms)", "number"),
      ro("resultStatus", "Result"),
    ],
    columns: [
      { key: "createdAt", label: "When" },
      { key: "_user", label: "User" },
      { key: "_question", label: "Question" },
      { key: "capability", label: "Capability" },
      { key: "_cited", label: "Cited" },
      { key: "estimatedTokens", label: "Tokens" },
      { key: "resultStatus", label: "Result" },
    ],
    create: false,
    edit: false,
    remove: false,
    hint: "Every question asked of Heritage AI in any portal, with the sources it cited.",
  },
  knowledge: {
    module: "ai",
    label: "Knowledge Source",
    plural: "Knowledge Sources",
    store: "table",
    screen: "OPS:AI_KNOWLEDGE",
    fields: [
      f("title", "Title", "text", { required: true }),
      f("slug", "Key", "text", { required: true, hint: "Unique, lowercase, e.g. student-handbook" }),
      sel("docType", "Type", ["student_handbook", "program_handbook", "admissions_policy", "academic_calendar", "course_material", "policy", "faq"]),
      f("uri", "Source Link", "text", { required: true }),
      f("versionLabel", "Version", "text", { required: true, dflt: "1" }),
      sel("status", "Status", ["published", "draft", "retired"]),
      f("body", "Content", "textarea", { required: true, long: true }),
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "docType", label: "Type" },
      { key: "versionLabel", label: "Version" },
      { key: "_size", label: "Size" },
      { key: "_cited", label: "Times Cited" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "docType"],
    actions: [act("publish", "Publish", { status: "published" }, { status: ["draft", "retired"] }, "primary"), act("retire", "Retire", { status: "retired" }, { status: ["published"] })],
    hint: "Published sources are what Heritage AI grounds its answers on.",
  },

  /* ----------------------------- Platform ----------------------------- */
  sessions: {
    module: "platform",
    label: "Session",
    plural: "Login Sessions",
    store: "table",
    screen: "OPS:PL_SESSION",
    fields: [ro("_account", "Account"), ro("ipAddress", "IP Address"), ro("userAgent", "Browser"), ro("deviceFingerprint", "Device"), ro("geoLocation", "Location"), ro("createdAt", "Signed In", "datetime"), ro("expiresAt", "Expires", "datetime"), ro("_state", "State")],
    columns: [
      { key: "createdAt", label: "Signed In" },
      { key: "_account", label: "Account" },
      { key: "ipAddress", label: "IP" },
      { key: "_browser", label: "Browser" },
      { key: "expiresAt", label: "Expires" },
      { key: "_state", label: "State" },
    ],
    actions: [{ key: "revoke", label: "Revoke", run: true, when: { _state: ["Active"] }, tone: "danger" }],
    create: false,
    edit: false,
    remove: false,
    hint: "Revoking ends the session; the user must sign in again once their current access token expires.",
  },
  auditLog: {
    module: "platform",
    label: "Audit Event",
    plural: "Audit Log",
    store: "table",
    screen: "OPS:PL_AUDIT",
    fields: [ro("createdAt", "When", "datetime"), ro("eventName", "Event"), ro("_actor", "Actor"), ro("purpose", "Purpose"), ro("source", "Source"), ro("correlationId", "Correlation"), ro("beforeJson", "Before", "textarea"), ro("afterJson", "After", "textarea")],
    columns: [
      { key: "createdAt", label: "When" },
      { key: "eventName", label: "Event" },
      { key: "_actor", label: "Actor" },
      { key: "source", label: "Source" },
    ],
    filters: ["eventName"],
    create: false,
    edit: false,
    remove: false,
    hint: "The latest 500 audit events across all portals.",
  },
  outbox: {
    module: "platform",
    label: "Event",
    plural: "Event Queue",
    store: "table",
    screen: "OPS:PL_OUTBOX",
    fields: [ro("eventName", "Event"), ro("status", "Status"), ro("attempts", "Attempts", "number"), ro("availableAt", "Next Attempt", "datetime"), ro("createdAt", "Queued", "datetime"), ro("payloadJson", "Payload", "textarea")],
    columns: [
      { key: "createdAt", label: "Queued" },
      { key: "eventName", label: "Event" },
      { key: "attempts", label: "Attempts" },
      { key: "availableAt", label: "Next Attempt" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "eventName"],
    actions: [
      { key: "requeue", label: "Retry Now", run: true, when: { status: ["failed", "dead", "pending", "discarded"] }, tone: "primary" },
      { key: "discard", label: "Discard", run: true, when: { status: ["failed", "dead", "pending"] }, tone: "danger" },
    ],
    create: false,
    edit: false,
    remove: false,
    hint: "Outbound events (notifications, integrations) waiting for the background worker.",
  },

  /* ----------------------------- Workspace ---------------------------- */
  notifications: {
    module: "workspace",
    label: "Notification",
    plural: "Notifications",
    store: "table",
    screen: "OPS:WS_NOTIFICATION",
    fields: [
      sel("audience", "Send To", ["One account", "All students", "All staff", "Everyone"], { createOnly: true }),
      f("recipientAccountId", "Recipient", "ref", { ref: "accounts", hint: "Required when sending to one account." }),
      sel("channel", "Channel", ["in_app", "email"]),
      f("title", "Title", "text", { required: true }),
      f("body", "Message", "textarea", { required: true }),
      ro("_state", "State"),
      ro("createdAt", "Sent", "datetime"),
    ],
    columns: [
      { key: "createdAt", label: "Sent" },
      { key: "recipientAccountId", label: "Recipient" },
      { key: "title", label: "Title" },
      { key: "channel", label: "Channel" },
      { key: "_mine", label: "Mine" },
      { key: "_state", label: "State" },
    ],
    filters: ["channel", "_state", "_mine"],
    actions: [{ key: "read", label: "Mark Read", run: true, when: { _state: ["Unread"] } }, { key: "unread", label: "Mark Unread", run: true, when: { _state: ["Read"] } }],
    edit: false,
    hint: "Recipients see these in their portal's notification bell.",
  },
  helpdesk: {
    module: "workspace",
    label: "Ticket",
    plural: "Help Desk",
    store: "record",
    screen: "OPS:WS_TICKET",
    fields: [
      f("subject", "Subject", "text", { required: true }),
      f("requesterId", "Requester", "ref", { ref: "accounts", required: true }),
      sel("category", "Category", ["Account & login", "Courses", "Finance", "Technical", "Facilities", "Other"]),
      sel("priority", "Priority", ["Normal", "Low", "High", "Urgent"]),
      f("assigneeId", "Assigned To", "ref", { ref: "staff" }),
      sel("status", "Status", ["Open", "In Progress", "Waiting", "Resolved", "Closed"]),
      f("description", "Description", "textarea", { required: true }),
      f("resolution", "Resolution", "textarea"),
    ],
    columns: [
      { key: "subject", label: "Subject" },
      { key: "requesterId", label: "Requester" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority" },
      { key: "assigneeId", label: "Assigned" },
      { key: "_age", label: "Age" },
      { key: "status", label: "Status" },
    ],
    filters: ["status", "priority", "category"],
    actions: [
      act("start", "Start", { status: "In Progress" }, { status: ["Open", "Waiting"] }, "primary"),
      act("wait", "Waiting on Requester", { status: "Waiting" }, { status: ["Open", "In Progress"] }),
      act("resolve", "Resolve", { status: "Resolved" }, { status: ["Open", "In Progress", "Waiting"] }, "primary"),
      act("close", "Close", { status: "Closed" }, { status: ["Resolved"] }),
      act("reopen", "Reopen", { status: "Open" }, { status: ["Resolved", "Closed"] }),
    ],
    hint: "Resolving requires a resolution note; the requester is notified when the ticket is resolved.",
  },
};

export const MORE_SLUGS: Record<MoreEntityKey, string> = {
  applications: "applications",
  appDocuments: "documents",
  interviews: "interviews",
  offers: "offers",
  intakes: "intakes",
  changeRequests: "change-requests",
  complianceCases: "cases",
  retention: "retention",
  legalHolds: "legal-holds",
  privacyRequests: "privacy-requests",
  evidence: "evidence",
  recordVault: "record-vault",
  disposals: "disposal-review",
  submissions: "submissions",
  ruleSets: "rule-sets",
  approvals: "requests",
  workflowDefs: "definitions",
  aiInteractions: "interactions",
  knowledge: "knowledge",
  sessions: "sessions",
  auditLog: "audit-log",
  outbox: "event-queue",
  notifications: "notifications",
  helpdesk: "help-desk",
};
