export type TaxPdfFields = {
  institutionName: string;
  legalName?: string | null;
  addressLine1?: string | null;
  city?: string | null;
  region?: string | null;
  postalCode?: string | null;
  country?: string | null;
  docType: string;
  title: string;
  taxYear: number;
  recipientName: string;
  recipientIdLabel: string;
  recipientId: string;
  programName?: string | null;
  eligibleTuitionCad?: number | null;
  enrolmentMonths?: number | null;
  sinLast4?: string | null;
  craStatus?: string | null;
  status: string;
  issuedAt: Date | string | null;
};

function winAnsi(text: string): string {
  return text
    .replace(/[–—]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, "...")
    .replace(/[^\x20-\x7E]/g, "?");
}

function pdfEscape(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLine(text: string, width = 88): string[] {
  const trimmed = text.trimEnd();
  if (!trimmed) return [""];
  const words = trimmed.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > width && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function formatCad(value: number): string {
  return `CAD ${value.toFixed(2)}`;
}

function formatIssued(issuedAt: Date | string | null): string {
  if (!issuedAt) return "Pending";
  const d = typeof issuedAt === "string" ? new Date(issuedAt) : issuedAt;
  if (Number.isNaN(d.getTime())) return "Pending";
  return d.toISOString().slice(0, 10);
}

function formatAddress(fields: TaxPdfFields): string {
  const cityLine = [fields.city, fields.region, fields.postalCode].filter(Boolean).join(", ");
  return [fields.addressLine1, cityLine, fields.country].filter(Boolean).join(" · ");
}

export function taxPdfFilename(docType: string, taxYear: number): string {
  const safe = docType.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "") || "tax";
  return `${safe}-${taxYear}.pdf`;
}

type DrawLine =
  | { kind: "text"; text: string; size: number; leading?: number }
  | { kind: "rule" }
  | { kind: "gap"; leading: number };

function buildBrandedPdf(lines: DrawLine[]): Buffer {
  const pageW = 612;
  const pageH = 792;
  const margin = 54;
  const ops: string[] = [];
  let y = pageH - 52;

  for (const line of lines) {
    if (y < 64) break;
    if (line.kind === "gap") {
      y -= line.leading;
      continue;
    }
    if (line.kind === "rule") {
      ops.push("q");
      ops.push("0.12 0.22 0.45 RG");
      ops.push("1.2 w");
      ops.push(`${margin} ${y} m ${pageW - margin} ${y} l S`);
      ops.push("Q");
      y -= 14;
      continue;
    }
    const size = line.size;
    const leading = line.leading ?? size + 4;
    for (const wrapped of wrapLine(winAnsi(line.text))) {
      if (y < 64) break;
      ops.push("BT");
      ops.push(`/F1 ${size} Tf`);
      ops.push("0.08 0.12 0.22 rg");
      ops.push(`${margin} ${y} Td`);
      ops.push(`(${pdfEscape(wrapped || " ")}) Tj`);
      ops.push("ET");
      y -= leading;
    }
  }

  // Footer brand bar
  ops.push("q");
  ops.push("0.12 0.22 0.45 rg");
  ops.push(`${margin} 36 ${pageW - margin * 2} 18 re f`);
  ops.push("Q");
  ops.push("BT");
  ops.push("/F1 8 Tf");
  ops.push("1 1 1 rg");
  ops.push(`${margin + 8} 41 Td`);
  ops.push(`(${pdfEscape("Heritage College  ·  Official tax document  ·  Generated by MyHeritage SIS")}) Tj`);
  ops.push("ET");

  const stream = ops.join("\n");
  const streamBytes = Buffer.byteLength(stream, "latin1");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>`,
    `<< /Length ${streamBytes} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefStart = Buffer.byteLength(pdf, "latin1");
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    xref += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `${xref}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return Buffer.from(pdf, "latin1");
}

/** @deprecated Prefer renderTaxCertificatePdf — kept for unit tests of raw PDF assembly. */
export function buildSimplePdf(title: string, bodyLines: string[]): Buffer {
  return buildBrandedPdf([
    { kind: "text", text: title, size: 16, leading: 22 },
    { kind: "rule" },
    ...bodyLines.map((text) => ({ kind: "text" as const, text, size: 11, leading: 15 })),
  ]);
}

export function sendPdf(res: { setHeader: (k: string, v: string) => void; send: (b: Buffer) => void }, pdf: Buffer, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${filename.replace(/"/g, "")}"`);
  res.setHeader("Cache-Control", "private, no-store");
  res.send(pdf);
}

export function renderTaxCertificatePdf(fields: TaxPdfFields): Buffer {
  const legal = fields.legalName || fields.institutionName;
  const address = formatAddress(fields);
  const lines: DrawLine[] = [
    { kind: "text", text: fields.institutionName.toUpperCase(), size: 18, leading: 22 },
    { kind: "text", text: legal, size: 10, leading: 13 },
  ];
  if (address) lines.push({ kind: "text", text: address, size: 9, leading: 12 });
  lines.push({ kind: "gap", leading: 6 });
  lines.push({ kind: "rule" });
  lines.push({ kind: "text", text: fields.title, size: 13, leading: 18 });
  lines.push({
    kind: "text",
    text: `Form ${fields.docType}  ·  Tax year ${fields.taxYear}`,
    size: 10,
    leading: 14,
  });
  lines.push({ kind: "gap", leading: 8 });
  lines.push({ kind: "text", text: "RECIPIENT", size: 9, leading: 12 });
  lines.push({ kind: "text", text: fields.recipientName, size: 12, leading: 16 });
  lines.push({
    kind: "text",
    text: `${fields.recipientIdLabel}: ${fields.recipientId}`,
    size: 10,
    leading: 14,
  });
  if (fields.programName) {
    lines.push({ kind: "text", text: `Program: ${fields.programName}`, size: 10, leading: 14 });
  }
  lines.push({ kind: "gap", leading: 8 });
  lines.push({ kind: "text", text: "CERTIFICATE DETAILS", size: 9, leading: 12 });
  if (fields.eligibleTuitionCad != null) {
    lines.push({
      kind: "text",
      text: `Eligible tuition fees: ${formatCad(fields.eligibleTuitionCad)}`,
      size: 11,
      leading: 15,
    });
  }
  if (fields.enrolmentMonths != null) {
    lines.push({
      kind: "text",
      text: `Months of enrolment (full-time / part-time): ${fields.enrolmentMonths}`,
      size: 11,
      leading: 15,
    });
  }
  if (fields.sinLast4) {
    lines.push({ kind: "text", text: `SIN (last 4 digits): ***${fields.sinLast4}`, size: 11, leading: 15 });
  }
  lines.push({
    kind: "text",
    text: `CRA / filing status: ${fields.craStatus || fields.status}`,
    size: 11,
    leading: 15,
  });
  lines.push({ kind: "text", text: `Issued: ${formatIssued(fields.issuedAt)}`, size: 11, leading: 15 });
  lines.push({ kind: "gap", leading: 10 });
  lines.push({ kind: "rule" });
  lines.push({
    kind: "text",
    text: "This is an official certificate issued by the institution for Canadian income-tax purposes.",
    size: 9,
    leading: 12,
  });
  lines.push({
    kind: "text",
    text: "Retain a copy with your tax records. Figures are derived from posted tuition ledger charges.",
    size: 9,
    leading: 12,
  });
  return buildBrandedPdf(lines);
}
