/** Canonical MyHeritage screen catalogue — synced from Figma inventory (deduped by path). */

export type ScreenEntry = {
  id: string;
  role: "student" | "instructor" | "admin" | "applicant" | "employer" | "shared" | "mobile" | "public";
  path: string;
  title: string;
  group: string;
  figmaId?: string;
};

export const ALL_SCREENS: ScreenEntry[] = [
  { id: "SH-18", role: "shared", path: "/accessibility", title: "sh-18-accessibility-statement", group: "Shared", figmaId: "66:828" },
  { id: "SH-11", role: "admin", path: "/admin", title: "sh-11-administration-home", group: "Shared", figmaId: "168:10" },
  { id: "AD-ALL", role: "admin", path: "/admin/all", title: "All admin screens", group: "Admin" },
  { id: "SH-13", role: "admin", path: "/admin/analytics", title: "sh-13-analytics-home", group: "Shared", figmaId: "66:270" },
  { id: "SH-12", role: "admin", path: "/admin/approvals", title: "sh-12-approval-inbox", group: "Shared", figmaId: "66:140" },
  { id: "SH-07", role: "admin", path: "/admin/calendar", title: "SH-07-Calendar", group: "Shared", figmaId: "17:13448" },
  { id: "AD-ENROL", role: "admin", path: "/admin/enrolments", title: "Enrolments", group: "Admin" },
  { id: "AC-01", role: "admin", path: "/admin/f/ac-01-academic-terms", title: "ac-01-academic-terms", group: "Admin", figmaId: "66:2707" },
  { id: "AC-02", role: "admin", path: "/admin/f/ac-02-academic-calendar", title: "ac-02-academic-calendar", group: "Admin", figmaId: "66:2852" },
  { id: "AC-03", role: "admin", path: "/admin/f/ac-03-programs", title: "ac-03-programs", group: "Admin", figmaId: "168:1713" },
  { id: "AC-04", role: "admin", path: "/admin/f/ac-04-program-detail", title: "ac-04-program-detail", group: "Admin", figmaId: "66:3189" },
  { id: "AC-05", role: "admin", path: "/admin/f/ac-05-program-change-request", title: "ac-05-program-change-request", group: "Admin", figmaId: "66:3307" },
  { id: "AC-06", role: "admin", path: "/admin/f/ac-06-course-catalogue", title: "ac-06-course-catalogue", group: "Admin", figmaId: "66:3469" },
  { id: "AC-07", role: "admin", path: "/admin/f/ac-07-course-setup", title: "ac-07-course-setup", group: "Admin", figmaId: "66:3610" },
  { id: "AC-08", role: "admin", path: "/admin/f/ac-08-course-categories", title: "ac-08-course-categories", group: "Admin", figmaId: "66:3730" },
  { id: "AC-09", role: "admin", path: "/admin/f/ac-09-sections", title: "ac-09-sections", group: "Admin", figmaId: "66:3847" },
  { id: "AC-10", role: "admin", path: "/admin/f/ac-10-master-scheduling", title: "ac-10-master-scheduling", group: "Admin", figmaId: "66:3982" },
  { id: "AC-11", role: "admin", path: "/admin/f/ac-11-pending-schedules", title: "ac-11-pending-schedules", group: "Admin", figmaId: "66:4235" },
  { id: "AC-12", role: "admin", path: "/admin/f/ac-12-grading-schemes", title: "ac-12-grading-schemes", group: "Admin", figmaId: "66:4424" },
  { id: "AC-13", role: "admin", path: "/admin/f/ac-13-pending-grades", title: "ac-13-pending-grades", group: "Admin", figmaId: "66:4615" },
  { id: "AC-14", role: "admin", path: "/admin/f/ac-14-faculty", title: "ac-14-faculty", group: "Admin", figmaId: "66:4809" },
  { id: "AC-15", role: "admin", path: "/admin/f/ac-15-course-evaluations", title: "ac-15-course-evaluations", group: "Admin", figmaId: "66:4968" },
  { id: "AC-16", role: "admin", path: "/admin/f/ac-16-course-resources", title: "ac-16-course-resources", group: "Admin", figmaId: "66:5364" },
  { id: "AC-17", role: "admin", path: "/admin/f/ac-17-student-requirements", title: "ac-17-student-requirements", group: "Admin", figmaId: "66:5552" },
  { id: "AC-18", role: "admin", path: "/admin/f/ac-18-loa-requests", title: "ac-18-loa-requests", group: "Admin", figmaId: "66:5700" },
  { id: "AC-19", role: "admin", path: "/admin/f/ac-19-withdraw-requests", title: "ac-19-withdraw-requests", group: "Admin", figmaId: "66:5844" },
  { id: "AC-20", role: "admin", path: "/admin/f/ac-20-create-student", title: "ac-20-create-student", group: "Admin", figmaId: "66:5975" },
  { id: "AD-01", role: "admin", path: "/admin/f/ad-01-admissions-dashboard", title: "ad-01-admissions-dashboard", group: "Admin", figmaId: "168:200" },
  { id: "AD-02", role: "admin", path: "/admin/f/ad-02-application-queue", title: "ad-02-application-queue", group: "Admin", figmaId: "168:408" },
  { id: "AD-03", role: "admin", path: "/admin/f/ad-03-application-detail", title: "ad-03-application-detail", group: "Admin", figmaId: "168:652" },
  { id: "AD-04", role: "admin", path: "/admin/f/ad-04-requirement-review", title: "ad-04-requirement-review", group: "Admin", figmaId: "17:14157" },
  { id: "AD-05", role: "admin", path: "/admin/f/ad-05-document-review", title: "ad-05-document-review", group: "Admin", figmaId: "17:14303" },
  { id: "AD-06", role: "admin", path: "/admin/f/ad-06-interview-workspace", title: "ad-06-interview-workspace", group: "Admin", figmaId: "17:14401" },
  { id: "AD-07", role: "admin", path: "/admin/f/ad-07-decision-workspace", title: "ad-07-decision-workspace", group: "Admin", figmaId: "17:14539" },
  { id: "AD-08", role: "admin", path: "/admin/f/ad-08-offer-builder", title: "ad-08-offer-builder", group: "Admin", figmaId: "17:14625" },
  { id: "AD-09", role: "admin", path: "/admin/f/ad-09-loa-builder", title: "ad-09-loa-builder", group: "Admin", figmaId: "17:14720" },
  { id: "AD-10", role: "admin", path: "/admin/f/ad-10-conversion", title: "ad-10-conversion", group: "Admin", figmaId: "17:14802" },
  { id: "AD-10", role: "admin", path: "/admin/f/ad-10-conversion-dashboard", title: "ad-10-conversion-dashboard", group: "Admin", figmaId: "134:181" },
  { id: "AD-11", role: "admin", path: "/admin/f/ad-11-intake-capacity", title: "ad-11-intake-capacity", group: "Admin", figmaId: "17:14890" },
  { id: "AI-01", role: "admin", path: "/admin/f/ai-01-ai-dashboard", title: "ai-01-ai-dashboard", group: "Admin", figmaId: "17:17016" },
  { id: "AI-02", role: "admin", path: "/admin/f/ai-02-model-registry", title: "ai-02-model-registry", group: "Admin", figmaId: "17:17225" },
  { id: "AI-03", role: "admin", path: "/admin/f/ai-03-prompt-registry", title: "ai-03-prompt-registry", group: "Admin", figmaId: "17:17388" },
  { id: "AI-04", role: "admin", path: "/admin/f/ai-04-tool-registry", title: "ai-04-tool-registry", group: "Admin", figmaId: "17:17552" },
  { id: "AI-05", role: "admin", path: "/admin/f/ai-05-knowledge-sources", title: "ai-05-knowledge-sources", group: "Admin", figmaId: "17:17707" },
  { id: "AI-06", role: "admin", path: "/admin/f/ai-06-ingestion-jobs", title: "ai-06-ingestion-jobs", group: "Admin", figmaId: "17:17852" },
  { id: "AI-07", role: "admin", path: "/admin/f/ai-07-retrieval-inspector", title: "ai-07-retrieval-inspector", group: "Admin", figmaId: "17:18180" },
  { id: "AI-08", role: "admin", path: "/admin/f/ai-08-evaluation-dashboard", title: "ai-08-evaluation-dashboard", group: "Admin", figmaId: "17:18303" },
  { id: "AI-09", role: "admin", path: "/admin/f/ai-09-citation-failures", title: "ai-09-citation-failures", group: "Admin", figmaId: "17:18428" },
  { id: "AI-10", role: "admin", path: "/admin/f/ai-10-usage-cost", title: "ai-10-usage-cost", group: "Admin", figmaId: "17:18538" },
  { id: "AI-11", role: "admin", path: "/admin/f/ai-11-ai-policy", title: "ai-11-ai-policy", group: "Admin", figmaId: "17:18639" },
  { id: "AI-12", role: "admin", path: "/admin/f/ai-12-tool-call-audit", title: "ai-12-tool-call-audit", group: "Admin", figmaId: "17:18712" },
  { id: "CP-01", role: "admin", path: "/admin/f/cp-01-compliance-dashboard", title: "cp-01-compliance-dashboard", group: "Admin", figmaId: "168:2399" },
  { id: "CP-02", role: "admin", path: "/admin/f/cp-02-record-completeness", title: "cp-02-record-completeness", group: "Admin", figmaId: "17:16000" },
  { id: "CP-03", role: "admin", path: "/admin/f/cp-03-record-vault", title: "cp-03-record-vault", group: "Admin", figmaId: "17:16137" },
  { id: "CP-04", role: "admin", path: "/admin/f/cp-04-retention-policies", title: "cp-04-retention-policies", group: "Admin", figmaId: "17:16235" },
  { id: "CP-05", role: "admin", path: "/admin/f/cp-05-legal-holds", title: "cp-05-legal-holds", group: "Admin", figmaId: "17:16334" },
  { id: "CP-06", role: "admin", path: "/admin/f/cp-06-evidence-mapping", title: "cp-06-evidence-mapping", group: "Admin", figmaId: "17:16423" },
  { id: "CP-07", role: "admin", path: "/admin/f/cp-07-accreditation-assistant", title: "cp-07-accreditation-assistant", group: "Admin", figmaId: "17:16529" },
  { id: "CP-08", role: "admin", path: "/admin/f/cp-08-inspection-pack", title: "cp-08-inspection-pack", group: "Admin", figmaId: "65:4898" },
  { id: "CP-09", role: "admin", path: "/admin/f/cp-09-disposal-review", title: "cp-09-disposal-review", group: "Admin", figmaId: "17:16639" },
  { id: "CP-10", role: "admin", path: "/admin/f/cp-10-privacy-requests", title: "cp-10-privacy-requests", group: "Admin", figmaId: "17:16728" },
  { id: "CRM-01", role: "admin", path: "/admin/f/crm-01-dashboard", title: "crm-01-dashboard", group: "Admin", figmaId: "168:1959" },
  { id: "CRM-02", role: "admin", path: "/admin/f/crm-02-leads", title: "crm-02-leads", group: "Admin", figmaId: "17:8674" },
  { id: "CRM-03", role: "admin", path: "/admin/f/crm-03-lead-360", title: "crm-03-lead-360", group: "Admin", figmaId: "17:8811" },
  { id: "CRM-04", role: "admin", path: "/admin/f/crm-04-campaigns", title: "crm-04-campaigns", group: "Admin", figmaId: "17:8957" },
  { id: "CRM-05", role: "admin", path: "/admin/f/crm-05-campaign-detail", title: "crm-05-campaign-detail", group: "Admin", figmaId: "17:9050" },
  { id: "CRM-06", role: "admin", path: "/admin/f/crm-06-events", title: "crm-06-events", group: "Admin", figmaId: "17:9149" },
  { id: "CRM-07", role: "admin", path: "/admin/f/crm-07-counsellor-queue", title: "crm-07-counsellor-queue", group: "Admin", figmaId: "17:9244" },
  { id: "CRM-08", role: "admin", path: "/admin/f/crm-08-funnel-analytics", title: "crm-08-funnel-analytics", group: "Admin", figmaId: "17:9338" },
  { id: "FM-01", role: "admin", path: "/admin/f/fm-01-form-list", title: "FM-01-Form-List", group: "Admin", figmaId: "17:13147" },
  { id: "FM-02", role: "admin", path: "/admin/f/fm-02-form-designer", title: "FM-02-Form-Designer", group: "Admin", figmaId: "17:13209" },
  { id: "FM-03", role: "admin", path: "/admin/f/fm-03-form-version", title: "FM-03-Form-Version", group: "Admin", figmaId: "17:13281" },
  { id: "FM-04", role: "admin", path: "/admin/f/fm-04-form-submissions", title: "FM-04-Form-Submissions", group: "Admin", figmaId: "17:13330" },
  { id: "FN-01", role: "admin", path: "/admin/f/fn-01-finance-dashboard", title: "FN-01 Finance Dashboard", group: "Admin", figmaId: "168:896" },
  { id: "FN-02", role: "admin", path: "/admin/f/fn-02-student-account", title: "fn-02-student-account", group: "Admin", figmaId: "65:4530" },
  { id: "FN-03", role: "admin", path: "/admin/f/fn-03-charges", title: "FN-03 Charges", group: "Admin", figmaId: "17:10809" },
  { id: "FN-04", role: "admin", path: "/admin/f/fn-04-payments", title: "FN-04 Payments", group: "Admin", figmaId: "17:10906" },
  { id: "FN-05", role: "admin", path: "/admin/f/fn-05-reconciliation", title: "FN-05 Reconciliation", group: "Admin", figmaId: "17:11000" },
  { id: "FN-06", role: "admin", path: "/admin/f/fn-06-refund-queue", title: "FN-06 Refund Queue", group: "Admin", figmaId: "17:11088" },
  { id: "FN-07", role: "admin", path: "/admin/f/fn-07-holds", title: "FN-07 Holds", group: "Admin", figmaId: "17:11179" },
  { id: "FN-08", role: "admin", path: "/admin/f/fn-08-finance-export", title: "fn-08-finance-export", group: "Admin", figmaId: "17:20634" },
  { id: "LB-01", role: "admin", path: "/admin/f/lb-01-lab-dashboard", title: "LB-01-Lab-Dashboard", group: "Admin", figmaId: "168:2186" },
  { id: "LB-02", role: "admin", path: "/admin/f/lb-02-lab-rooms", title: "lb-02-lab-rooms", group: "Admin", figmaId: "65:1833" },
  { id: "LB-03", role: "admin", path: "/admin/f/lb-03-lab-equipment-list", title: "LB-03-Lab-Equipment-List", group: "Admin", figmaId: "17:11504" },
  { id: "LB-04", role: "admin", path: "/admin/f/lb-04-equipment-detail", title: "lb-04-equipment-detail", group: "Admin", figmaId: "65:2077" },
  { id: "LB-05", role: "admin", path: "/admin/f/lb-05-inventory", title: "lb-05-inventory", group: "Admin", figmaId: "65:2226" },
  { id: "LB-06", role: "admin", path: "/admin/f/lb-06-safety-rules", title: "lb-06-safety-rules", group: "Admin", figmaId: "65:2389" },
  { id: "LB-07", role: "admin", path: "/admin/f/lb-07-student-eligibility", title: "lb-07-student-eligibility", group: "Admin", figmaId: "65:2673" },
  { id: "LB-08", role: "admin", path: "/admin/f/lb-08-lab-session", title: "lb-08-lab-session", group: "Admin", figmaId: "17:2790" },
  { id: "LB-09", role: "admin", path: "/admin/f/lb-09-lab-notebook", title: "LB-09-Lab-Notebook", group: "Admin", figmaId: "17:11624" },
  { id: "LB-10", role: "admin", path: "/admin/f/lb-10-incident", title: "lb-10-incident", group: "Admin", figmaId: "65:2852" },
  { id: "LB-11", role: "admin", path: "/admin/f/lb-11-virtual-labs", title: "lb-11-virtual-labs", group: "Admin", figmaId: "65:2986" },
  { id: "LB-12", role: "admin", path: "/admin/f/lb-12-computer-environments", title: "lb-12-computer-environments", group: "Admin", figmaId: "65:3146" },
  { id: "PL-01", role: "admin", path: "/admin/f/pl-01-users-and-roles", title: "pl-01-users-and-roles", group: "Admin", figmaId: "168:2613" },
  { id: "PL-02", role: "admin", path: "/admin/f/pl-02-permission-matrix", title: "pl-02-permission-matrix", group: "Admin", figmaId: "66:1314" },
  { id: "PL-03", role: "admin", path: "/admin/f/pl-03-security-policy", title: "pl-03-security-policy", group: "Admin", figmaId: "66:1483" },
  { id: "PL-04", role: "admin", path: "/admin/f/pl-04-session-login-audit", title: "pl-04-session-login-audit", group: "Admin", figmaId: "66:1608" },
  { id: "PL-05", role: "admin", path: "/admin/f/pl-05-integrations", title: "pl-05-integrations", group: "Admin", figmaId: "66:1977" },
  { id: "PL-06", role: "admin", path: "/admin/f/pl-06-operations", title: "pl-06-operations", group: "Admin", figmaId: "66:2137" },
  { id: "PL-07", role: "admin", path: "/admin/f/pl-07-institution-settings", title: "pl-07-institution-settings", group: "Admin", figmaId: "66:2284" },
  { id: "PL-08", role: "admin", path: "/admin/f/pl-08-notification-templates", title: "pl-08-notification-templates", group: "Admin", figmaId: "66:2385" },
  { id: "PR-01", role: "admin", path: "/admin/f/pr-01-practicum-dashboard", title: "PR-01-Practicum-Dashboard", group: "Admin", figmaId: "17:11726" },
  { id: "PR-02", role: "admin", path: "/admin/f/pr-02-employers-registry", title: "PR-02-Employers-Registry", group: "Admin", figmaId: "17:11883" },
  { id: "PR-03", role: "admin", path: "/admin/f/pr-03-sites", title: "pr-03-sites", group: "Admin", figmaId: "65:3354" },
  { id: "PR-04", role: "admin", path: "/admin/f/pr-04-opportunities", title: "pr-04-opportunities", group: "Admin", figmaId: "65:3508" },
  { id: "PR-05", role: "admin", path: "/admin/f/pr-05-placements-workspace", title: "PR-05-Placements-Workspace", group: "Admin", figmaId: "17:12002" },
  { id: "PR-06", role: "admin", path: "/admin/f/pr-06-agreements", title: "pr-06-agreements", group: "Admin", figmaId: "65:3725" },
  { id: "PR-07", role: "admin", path: "/admin/f/pr-07-logs", title: "pr-07-logs", group: "Admin", figmaId: "65:3846" },
  { id: "PR-08", role: "admin", path: "/admin/f/pr-08-evaluations", title: "pr-08-evaluations", group: "Admin", figmaId: "65:4101" },
  { id: "PR-09", role: "admin", path: "/admin/f/pr-09-incidents", title: "pr-09-incidents", group: "Admin", figmaId: "65:4279" },
  { id: "PR-10", role: "admin", path: "/admin/f/pr-10-employer-portal", title: "pr-10-employer-portal", group: "Admin", figmaId: "65:4416" },
  { id: "RG-00", role: "admin", path: "/admin/f/rg-00-registrar-dashboard", title: "RG-00 Registrar Dashboard", group: "Admin", figmaId: "168:2826" },
  { id: "RG-01", role: "admin", path: "/admin/f/rg-01-student-360", title: "rg-01-student-360", group: "Admin", figmaId: "17:1049" },
  { id: "RG-02", role: "admin", path: "/admin/f/rg-02-academic-history", title: "rg-02-academic-history", group: "Admin", figmaId: "17:15028" },
  { id: "RG-03", role: "admin", path: "/admin/f/rg-03-status-history", title: "rg-03-status-history", group: "Admin", figmaId: "17:15181" },
  { id: "RG-04", role: "admin", path: "/admin/f/rg-04-transfer-credits", title: "rg-04-transfer-credits", group: "Admin", figmaId: "17:15305" },
  { id: "RG-05", role: "admin", path: "/admin/f/rg-05-academic-standing", title: "rg-05-academic-standing", group: "Admin", figmaId: "17:15432" },
  { id: "RG-06", role: "admin", path: "/admin/f/rg-06-completion-audit", title: "rg-06-completion-audit", group: "Admin", figmaId: "17:15554" },
  { id: "RG-07", role: "admin", path: "/admin/f/rg-07-transcript", title: "rg-07-transcript", group: "Admin", figmaId: "17:15688" },
  { id: "RG-08", role: "admin", path: "/admin/f/rg-08-registrar-correction", title: "rg-08-registrar-correction", group: "Admin", figmaId: "17:15786" },
  { id: "RG-09", role: "admin", path: "/admin/f/rg-09-official-export", title: "rg-09-official-export", group: "Admin", figmaId: "17:15865" },
  { id: "RL-01", role: "admin", path: "/admin/f/rl-01-rule-sets", title: "RL-01-Rule-Sets", group: "Admin", figmaId: "17:12957" },
  { id: "RL-02", role: "admin", path: "/admin/f/rl-02-rule-designer", title: "RL-02-Rule-Designer", group: "Admin", figmaId: "17:13019" },
  { id: "RL-03", role: "admin", path: "/admin/f/rl-03-rule-simulator", title: "RL-03-Rule-Simulator", group: "Admin", figmaId: "17:13085" },
  { id: "SH-01", role: "admin", path: "/admin/f/sh-01-login-admin", title: "sh-01-login (Admin)", group: "Admin", figmaId: "27:118" },
  { id: "SS-01", role: "admin", path: "/admin/f/ss-01-success-dashboard", title: "SS-01 Success Dashboard", group: "Admin", figmaId: "168:1117" },
  { id: "SS-02", role: "admin", path: "/admin/f/ss-02-alert-queue", title: "SS-02 Alert Queue", group: "Admin", figmaId: "17:10106" },
  { id: "SS-03", role: "admin", path: "/admin/f/ss-03-student-success-360", title: "SS-03 Student Success 360", group: "Admin", figmaId: "17:10211" },
  { id: "SS-04", role: "admin", path: "/admin/f/ss-04-case", title: "SS-04 Case", group: "Admin", figmaId: "17:10294" },
  { id: "SS-05", role: "admin", path: "/admin/f/ss-05-action-plan", title: "SS-05 Action Plan", group: "Admin", figmaId: "17:10379" },
  { id: "SS-06", role: "admin", path: "/admin/f/ss-06-appointments", title: "SS-06 Appointments", group: "Admin", figmaId: "17:10486" },
  { id: "SS-07", role: "admin", path: "/admin/f/ss-07-intervention-analytics", title: "SS-07 Intervention Analytics", group: "Admin", figmaId: "17:10585" },
  { id: "WF-01", role: "admin", path: "/admin/f/wf-01-workflow-list", title: "WF-01-Workflow-List", group: "Admin", figmaId: "17:12751" },
  { id: "WF-02", role: "admin", path: "/admin/f/wf-02-workflow-designer", title: "wf-02-workflow-designer", group: "Admin", figmaId: "17:2903" },
  { id: "WF-03", role: "admin", path: "/admin/f/wf-03-workflow-test", title: "WF-03-Workflow-Test", group: "Admin", figmaId: "17:12828" },
  { id: "WF-04", role: "admin", path: "/admin/f/wf-04-workflow-runs", title: "WF-04-Workflow-Runs", group: "Admin", figmaId: "17:12879" },
  { id: "XX-1", role: "admin", path: "/admin/f/xx-1-lab-booking-calendar", title: "xx-1-lab-booking-calendar", group: "Admin", figmaId: "71:13" },
  { id: "XX-2", role: "admin", path: "/admin/f/xx-2-lab-usage-analytics", title: "xx-2-lab-usage-analytics", group: "Admin", figmaId: "71:195" },
  { id: "XX-3", role: "admin", path: "/admin/f/xx-3-simulation-templates", title: "xx-3-simulation-templates", group: "Admin", figmaId: "71:436" },
  { id: "XX-4", role: "admin", path: "/admin/f/xx-4-lab-compliance", title: "xx-4-lab-compliance", group: "Admin", figmaId: "71:567" },
  { id: "XX-5", role: "admin", path: "/admin/f/xx-5-preceptor-management", title: "xx-5-preceptor-management", group: "Admin", figmaId: "71:709" },
  { id: "XX-6", role: "admin", path: "/admin/f/xx-6-competency-tracking", title: "xx-6-competency-tracking", group: "Admin", figmaId: "71:1016" },
  { id: "XX-7", role: "admin", path: "/admin/f/xx-7-clinical-compliance", title: "xx-7-clinical-compliance", group: "Admin", figmaId: "71:1203" },
  { id: "XX-8", role: "admin", path: "/admin/f/xx-8-practicum-reports", title: "xx-8-practicum-reports", group: "Admin", figmaId: "71:1364" },
  { id: "XX-9", role: "admin", path: "/admin/f/xx-9-disposal-review-queue", title: "xx-9-disposal-review-queue", group: "Admin", figmaId: "71:1516" },
  { id: "SH-05", role: "admin", path: "/admin/notifications", title: "SH-05-Notifications", group: "Shared", figmaId: "17:13425" },
  { id: "SH-08", role: "admin", path: "/admin/profile", title: "SH-08-Profile", group: "Shared", figmaId: "17:13515" },
  { id: "SH-06", role: "admin", path: "/admin/search", title: "sh-06-universal-search", group: "Shared", figmaId: "178:121" },
  { id: "AD-CREATE-SECTION", role: "admin", path: "/admin/sections/create", title: "Create section", group: "Admin" },
  { id: "SH-09", role: "admin", path: "/admin/security", title: "SH-09-Security", group: "Shared", figmaId: "17:13574" },
  { id: "AD-USERS", role: "admin", path: "/admin/users", title: "Users & roles", group: "Admin" },
  { id: "AD-CREATE-USER", role: "admin", path: "/admin/users/create", title: "Create user", group: "Admin" },
  { id: "AP-01", role: "applicant", path: "/applicant", title: "ap-01-applicant-dashboard", group: "Applicant", figmaId: "17:1673" },
  { id: "AP-02", role: "applicant", path: "/applicant/application", title: "ap-02-application-wizard", group: "Applicant", figmaId: "17:1795" },
  { id: "AP-04", role: "applicant", path: "/applicant/documents", title: "ap-04-documents", group: "Applicant", figmaId: "17:5512" },
  { id: "AP-03", role: "applicant", path: "/applicant/f/ap-03-requirements", title: "ap-03-requirements", group: "Applicant", figmaId: "17:5399" },
  { id: "AP-05", role: "applicant", path: "/applicant/f/ap-05-interview", title: "ap-05-interview", group: "Applicant", figmaId: "17:5615" },
  { id: "AP-06", role: "applicant", path: "/applicant/f/ap-06-application-status", title: "ap-06-application-status", group: "Applicant", figmaId: "17:5745" },
  { id: "AP-08", role: "applicant", path: "/applicant/f/ap-08-contract", title: "ap-08-contract", group: "Applicant", figmaId: "17:5927" },
  { id: "AP-09", role: "applicant", path: "/applicant/f/ap-09-loa", title: "ap-09-loa", group: "Applicant", figmaId: "17:6009" },
  { id: "AP-10", role: "applicant", path: "/applicant/f/ap-10-payment", title: "ap-10-payment", group: "Applicant", figmaId: "17:6095" },
  { id: "AP-11", role: "applicant", path: "/applicant/f/ap-11-onboarding", title: "ap-11-onboarding", group: "Applicant", figmaId: "17:6200" },
  { id: "AP-12", role: "applicant", path: "/applicant/f/ap-12-applicant-ai-drawer", title: "ap-12-applicant-ai-drawer", group: "Applicant", figmaId: "17:6292" },
  { id: "AP-07", role: "applicant", path: "/applicant/offers", title: "ap-07-offer", group: "Applicant", figmaId: "17:5842" },
  { id: "UI-state-archived", role: "shared", path: "/archive", title: "state-archived", group: "Design System", figmaId: "26:1017" },
  { id: "SH-14", role: "shared", path: "/denied", title: "sh-14-error-404", group: "Shared", figmaId: "66:390" },
  { id: "UI-component-library-button", role: "shared", path: "/design-system", title: "component-library-buttons-inputs", group: "Design System", figmaId: "26:6" },
  { id: "FD-05", role: "shared", path: "/design-system/breakpoints", title: "fd-05-responsive-breakpoints", group: "Design System", figmaId: "66:7864" },
  { id: "UI-component-library-cards-", role: "shared", path: "/design-system/cards", title: "component-library-cards-tables-status", group: "Design System", figmaId: "26:155" },
  { id: "UI-component-library-patter", role: "shared", path: "/design-system/patterns", title: "component-library-patterns-states", group: "Design System", figmaId: "26:328" },
  { id: "UI-admin-shell-component", role: "shared", path: "/design-system/shell", title: "admin-shell-component", group: "Design System", figmaId: "65:5712" },
  { id: "UI-state-empty", role: "shared", path: "/design-system/state-empty", title: "state-empty", group: "Design System", figmaId: "26:704" },
  { id: "UI-state-error", role: "shared", path: "/design-system/state-error", title: "state-error", group: "Design System", figmaId: "26:771" },
  { id: "UI-state-loading", role: "shared", path: "/design-system/state-loading", title: "state-loading", group: "Design System", figmaId: "26:613" },
  { id: "UI-design-tokens-sheet", role: "shared", path: "/design-system/tokens", title: "design-tokens-sheet", group: "Design System", figmaId: "65:5363" },
  { id: "DC-01", role: "shared", path: "/docs/f/dc-01-transcript-pdf", title: "dc-01-transcript-pdf", group: "Documents", figmaId: "66:6290" },
  { id: "DC-02", role: "shared", path: "/docs/f/dc-02-loa-ircc-compliant", title: "dc-02-loa-ircc-compliant", group: "Documents", figmaId: "102:1941" },
  { id: "DC-02", role: "shared", path: "/docs/f/dc-02-loa-pdf", title: "dc-02-loa-pdf", group: "Documents", figmaId: "66:6386" },
  { id: "DC-03", role: "shared", path: "/docs/f/dc-03-offer-pdf", title: "dc-03-offer-pdf", group: "Documents", figmaId: "66:6442" },
  { id: "DC-04", role: "shared", path: "/docs/f/dc-04-contract-pdf", title: "dc-04-contract-pdf", group: "Documents", figmaId: "66:6500" },
  { id: "DC-05", role: "shared", path: "/docs/f/dc-05-fee-receipt-pdf", title: "dc-05-fee-receipt-pdf", group: "Documents", figmaId: "66:6852" },
  { id: "DC-06", role: "shared", path: "/docs/f/dc-06-id-card-template", title: "dc-06-id-card-template", group: "Documents", figmaId: "66:6942" },
  { id: "DC-07", role: "shared", path: "/docs/f/dc-07-email-template", title: "dc-07-email-template", group: "Documents", figmaId: "66:7025" },
  { id: "DC-07", role: "shared", path: "/docs/f/dc-07-tablet-attendance", title: "dc-07-tablet-attendance", group: "Documents", figmaId: "102:888" },
  { id: "SH-17", role: "shared", path: "/help", title: "sh-17-help-centre", group: "Shared", figmaId: "66:697" },
  { id: "T01", role: "instructor", path: "/instructor", title: "T01 - Teacher Dashboard", group: "Teacher", figmaId: "3:3698" },
  { id: "IN-ALL", role: "instructor", path: "/instructor/all", title: "All teacher screens", group: "Teacher" },
  { id: "T09", role: "instructor", path: "/instructor/attendance", title: "T09 — Attendance Session", group: "Teacher", figmaId: "3:4952" },
  { id: "T18", role: "instructor", path: "/instructor/calendar", title: "T18 — Full Calendar / Timetable", group: "Teacher", figmaId: "4:6547" },
  { id: "IN-03", role: "instructor", path: "/instructor/f/in-03-course-detail", title: "in-03-course-detail", group: "Teacher", figmaId: "17:6652" },
  { id: "IN-04", role: "instructor", path: "/instructor/f/in-04-roster", title: "in-04-roster", group: "Teacher", figmaId: "17:6739" },
  { id: "IN-06", role: "instructor", path: "/instructor/f/in-06-assessment-manager", title: "in-06-assessment-manager", group: "Teacher", figmaId: "17:6962" },
  { id: "IN-08", role: "instructor", path: "/instructor/f/in-08-lectures", title: "in-08-lectures", group: "Teacher", figmaId: "17:7058" },
  { id: "IN-09", role: "instructor", path: "/instructor/f/in-09-lecture-review", title: "in-09-lecture-review", group: "Teacher", figmaId: "17:7147" },
  { id: "IN-10", role: "instructor", path: "/instructor/f/in-10-lab-sessions", title: "in-10-lab-sessions", group: "Teacher", figmaId: "17:7217" },
  { id: "IN-11", role: "instructor", path: "/instructor/f/in-11-student-detail", title: "in-11-student-detail", group: "Teacher", figmaId: "17:7313" },
  { id: "IN-12", role: "instructor", path: "/instructor/f/in-12-ai-course-studio", title: "in-12-ai-course-studio", group: "Teacher", figmaId: "17:7388" },
  { id: "IN-13", role: "instructor", path: "/instructor/f/in-13-studio-generation", title: "in-13-studio-generation", group: "Teacher", figmaId: "17:7479" },
  { id: "IN-14", role: "instructor", path: "/instructor/f/in-14-outcome-mapping", title: "in-14-outcome-mapping", group: "Teacher", figmaId: "17:7596" },
  { id: "IN-15", role: "instructor", path: "/instructor/f/in-15-question-generator", title: "in-15-question-generator", group: "Teacher", figmaId: "17:7724" },
  { id: "IN-16", role: "instructor", path: "/instructor/f/in-16-rubric-generator", title: "in-16-rubric-generator", group: "Teacher", figmaId: "17:7830" },
  { id: "IN-17", role: "instructor", path: "/instructor/f/in-17-course-approval", title: "in-17-course-approval", group: "Teacher", figmaId: "17:7922" },
  { id: "IN-18", role: "instructor", path: "/instructor/f/in-18-availability", title: "in-18-availability", group: "Teacher", figmaId: "17:8021" },
  { id: "IN-19", role: "instructor", path: "/instructor/f/in-19-compensation", title: "in-19-compensation", group: "Teacher", figmaId: "17:8223" },
  { id: "IN-20", role: "instructor", path: "/instructor/f/in-20-workshops", title: "in-20-workshops", group: "Teacher", figmaId: "17:8317" },
  { id: "T02", role: "instructor", path: "/instructor/f/t02-profile-biography", title: "T02 — Profile: Biography", group: "Teacher", figmaId: "3:3890" },
  { id: "T03", role: "instructor", path: "/instructor/f/t03-profile-topics", title: "T03 — Profile: Topics", group: "Teacher", figmaId: "3:4011" },
  { id: "T04", role: "instructor", path: "/instructor/f/t04-profile-availability", title: "T04 — Profile: Availability", group: "Teacher", figmaId: "3:4135" },
  { id: "T05", role: "instructor", path: "/instructor/f/t05-profile-compensation", title: "T05 — Profile: Compensation", group: "Teacher", figmaId: "3:4278" },
  { id: "T06", role: "instructor", path: "/instructor/f/t06-profile-schedule", title: "T06 — Profile: Schedule", group: "Teacher", figmaId: "3:4396" },
  { id: "T08", role: "instructor", path: "/instructor/f/t08-my-courses-detail", title: "T08 — My Courses: Detail", group: "Teacher", figmaId: "3:4781" },
  { id: "T10", role: "instructor", path: "/instructor/f/t10-assessments-gradebook", title: "T10 — Assessments & Gradebook", group: "Teacher", figmaId: "3:5121" },
  { id: "T11", role: "instructor", path: "/instructor/f/t11-workshops", title: "T11 — Workshops", group: "Teacher", figmaId: "3:5292" },
  { id: "T12", role: "instructor", path: "/instructor/f/t12-students-view", title: "T12 — Students View", group: "Teacher", figmaId: "3:5401" },
  { id: "T13", role: "instructor", path: "/instructor/f/t13-program-management", title: "T13 — Program Management", group: "Teacher", figmaId: "3:5572" },
  { id: "T14", role: "instructor", path: "/instructor/f/t14-course-management", title: "T14 — Course Management", group: "Teacher", figmaId: "3:5722" },
  { id: "T15", role: "instructor", path: "/instructor/f/t15-settings", title: "T15 — Settings", group: "Teacher", figmaId: "3:5875" },
  { id: "T16", role: "instructor", path: "/instructor/f/t16-teacher-messages-chat", title: "T16 — Teacher Messages & Chat", group: "Teacher", figmaId: "4:6136" },
  { id: "T19", role: "instructor", path: "/instructor/f/t19-create-edit-assessment", title: "T19 — Create/Edit Assessment", group: "Teacher", figmaId: "4:6721" },
  { id: "T20", role: "instructor", path: "/instructor/f/t20-grade-correction-workflow", title: "T20 — Grade Correction Workflow", group: "Teacher", figmaId: "4:6864" },
  { id: "T21", role: "instructor", path: "/instructor/f/t21-attendance-correction-review", title: "T21 — Attendance Correction Review", group: "Teacher", figmaId: "4:7002" },
  { id: "T22", role: "instructor", path: "/instructor/f/t22-student-detail-full-page", title: "T22 — Student Detail Full Page", group: "Teacher", figmaId: "4:7293" },
  { id: "T23", role: "instructor", path: "/instructor/f/t23-course-announcements", title: "T23 — Course Announcements", group: "Teacher", figmaId: "4:7509" },
  { id: "T24", role: "instructor", path: "/instructor/f/t24-workshop-detail", title: "T24 — Workshop Detail", group: "Teacher", figmaId: "4:7678" },
  { id: "T25", role: "instructor", path: "/instructor/f/t25-add-availability-modal", title: "T25 — Add Availability Modal", group: "Teacher", figmaId: "4:7837" },
  { id: "T26", role: "instructor", path: "/instructor/f/t26-course-version-editor", title: "T26 — Course Version Editor", group: "Teacher", figmaId: "4:7961" },
  { id: "T27", role: "instructor", path: "/instructor/f/t27-program-change-request", title: "T27 — Program Change Request", group: "Teacher", figmaId: "4:8112" },
  { id: "T29", role: "instructor", path: "/instructor/f/t29-password-reset-flow", title: "T29 — Password Reset Flow", group: "Teacher", figmaId: "4:8499" },
  { id: "T30", role: "instructor", path: "/instructor/f/t30-mfa-challenge", title: "T30 — MFA Challenge", group: "Teacher", figmaId: "4:8586" },
  { id: "T31", role: "instructor", path: "/instructor/f/t31-first-login-profile-completion", title: "T31 — First Login / Profile Completion", group: "Teacher", figmaId: "4:8650" },
  { id: "T32", role: "instructor", path: "/instructor/f/t32-resource-file-manager", title: "T32 — Resource / File Manager", group: "Teacher", figmaId: "4:8858" },
  { id: "T33", role: "instructor", path: "/instructor/f/t33-help-support", title: "T33 — Help & Support", group: "Teacher", figmaId: "4:9078" },
  { id: "T34", role: "instructor", path: "/instructor/f/t34-accomplishments", title: "T34 — Accomplishments", group: "Teacher", figmaId: "4:10861" },
  { id: "T35", role: "instructor", path: "/instructor/f/t35-security-settings", title: "T35 — Security Settings", group: "Teacher", figmaId: "4:11045" },
  { id: "T36", role: "instructor", path: "/instructor/f/t36-course-evaluations", title: "T36 — Course Evaluations", group: "Teacher", figmaId: "4:11188" },
  { id: "T37", role: "instructor", path: "/instructor/f/t37-course-repository", title: "T37 — Course Repository", group: "Teacher", figmaId: "4:11353" },
  { id: "T38", role: "instructor", path: "/instructor/f/t38-pending-course-schedules", title: "T38 — Pending Course Schedules", group: "Teacher", figmaId: "4:11508" },
  { id: "T39", role: "instructor", path: "/instructor/f/t39-course-history", title: "T39 — Course History", group: "Teacher", figmaId: "4:11657" },
  { id: "T40", role: "instructor", path: "/instructor/f/t40-workshop-enrollment-status", title: "T40 — Workshop Enrollment Status", group: "Teacher", figmaId: "4:11882" },
  { id: "T41", role: "instructor", path: "/instructor/f/t41-workshop-attendance", title: "T41 — Workshop Attendance", group: "Teacher", figmaId: "4:12042" },
  { id: "T42", role: "instructor", path: "/instructor/f/t42-new-workshop-enrollment", title: "T42 — New Workshop Enrollment", group: "Teacher", figmaId: "4:12222" },
  { id: "T43", role: "instructor", path: "/instructor/f/t43-create-student-profile", title: "T43 — Create Student Profile", group: "Teacher", figmaId: "4:12383" },
  { id: "T44", role: "instructor", path: "/instructor/f/t44-academic-alerts", title: "T44 — Academic Alerts", group: "Teacher", figmaId: "4:12498" },
  { id: "T45", role: "instructor", path: "/instructor/f/t45-student-flags", title: "T45 — Student Flags", group: "Teacher", figmaId: "4:12620" },
  { id: "T46", role: "instructor", path: "/instructor/f/t46-student-assessments", title: "T46 — Student Assessments", group: "Teacher", figmaId: "4:12840" },
  { id: "T47", role: "instructor", path: "/instructor/f/t47-student-requirements", title: "T47 — Student Requirements", group: "Teacher", figmaId: "4:13060" },
  { id: "T48", role: "instructor", path: "/instructor/f/t48-leave-of-absence", title: "T48 — Leave of Absence", group: "Teacher", figmaId: "4:13242" },
  { id: "T49", role: "instructor", path: "/instructor/f/t49-course-withdraw-requests", title: "T49 — Course Withdraw Requests", group: "Teacher", figmaId: "4:13392" },
  { id: "T50", role: "instructor", path: "/instructor/f/t50-program-types", title: "T50 — Program Types", group: "Teacher", figmaId: "4:13533" },
  { id: "T51", role: "instructor", path: "/instructor/f/t51-manage-terms", title: "T51 — Manage Terms", group: "Teacher", figmaId: "4:13710" },
  { id: "T52", role: "instructor", path: "/instructor/f/t52-academic-calendars", title: "T52 — Academic Calendars", group: "Teacher", figmaId: "4:14049" },
  { id: "T53", role: "instructor", path: "/instructor/f/t53-master-scheduling", title: "T53 — Master Scheduling", group: "Teacher", figmaId: "4:14305" },
  { id: "T54", role: "instructor", path: "/instructor/f/t54-courses-sessions", title: "T54 — Courses & Sessions", group: "Teacher", figmaId: "4:14505" },
  { id: "T55", role: "instructor", path: "/instructor/f/t55-add-course-form", title: "T55 — Add Course Form", group: "Teacher", figmaId: "4:14670" },
  { id: "T56", role: "instructor", path: "/instructor/f/t56-active-courses", title: "T56 — Active Courses", group: "Teacher", figmaId: "4:14878" },
  { id: "T57", role: "instructor", path: "/instructor/f/t57-course-textbooks", title: "T57 — Course Textbooks", group: "Teacher", figmaId: "4:15104" },
  { id: "T58", role: "instructor", path: "/instructor/f/t58-course-categories", title: "T58 — Course Categories", group: "Teacher", figmaId: "4:15486" },
  { id: "T59", role: "instructor", path: "/instructor/f/t59-course-groups-types", title: "T59 — Course Groups & Types", group: "Teacher", figmaId: "4:15699" },
  { id: "T60", role: "instructor", path: "/instructor/f/t60-course-resources-management", title: "T60 — Course Resources Management", group: "Teacher", figmaId: "4:15877" },
  { id: "T61", role: "instructor", path: "/instructor/f/t61-grading-schemes", title: "T61 — Grading Schemes", group: "Teacher", figmaId: "4:16047" },
  { id: "T62", role: "instructor", path: "/instructor/f/t62-pending-grade-submissions", title: "T62 — Pending Grade Submissions", group: "Teacher", figmaId: "4:16245" },
  { id: "T63", role: "instructor", path: "/instructor/f/t63-students-by-status-filter", title: "T63 — Students by Status Filter", group: "Teacher", figmaId: "4:16388" },
  { id: "IN-07", role: "instructor", path: "/instructor/f/in-07-gradebook", title: "in-07-gradebook", group: "Teacher", figmaId: "17:775" },
  { id: "T17", role: "instructor", path: "/instructor/notifications", title: "T17 — Notification Center", group: "Teacher", figmaId: "4:6347" },
  { id: "T07", role: "instructor", path: "/instructor/sections", title: "T07 — My Courses: List", group: "Teacher", figmaId: "3:4608" },
  { id: "T28", role: "instructor", path: "/login", title: "T28 — Login Page", group: "Teacher", figmaId: "4:8396" },
  { id: "MB-03", role: "mobile", path: "/m/f/mb-03-mobile-schedule", title: "mb-03-mobile-schedule", group: "Mobile", figmaId: "66:7076" },
  { id: "MB-03", role: "mobile", path: "/m/f/mb-03-student-todo", title: "mb-03-student-todo", group: "Mobile", figmaId: "102:7" },
  { id: "MB-04", role: "mobile", path: "/m/f/mb-04-student-schedule", title: "mb-04-student-schedule", group: "Mobile", figmaId: "102:106" },
  { id: "MB-06", role: "mobile", path: "/m/f/mb-06-mobile-notifications", title: "mb-06-mobile-notifications", group: "Mobile", figmaId: "66:7253" },
  { id: "MB-09", role: "mobile", path: "/m/f/mb-09-notifications", title: "mb-09-notifications", group: "Mobile", figmaId: "102:203" },
  { id: "MB-10", role: "mobile", path: "/m/f/mb-10-offline-state", title: "mb-10-offline-state", group: "Mobile", figmaId: "102:303" },
  { id: "MB-07", role: "mobile", path: "/m/instructor/attendance", title: "mb-07-instructor-attendance", group: "Mobile", figmaId: "102:583" },
  { id: "MB-08", role: "mobile", path: "/m/instructor/grades", title: "mb-08-instructor-grading", group: "Mobile", figmaId: "102:750" },
  { id: "MB-06", role: "mobile", path: "/m/instructor/home", title: "mb-06-instructor-home", group: "Mobile", figmaId: "102:467" },
  { id: "MB-11", role: "mobile", path: "/m/login", title: "Mobile sign in", group: "Mobile" },
  { id: "SH-mobile-student-home", role: "mobile", path: "/m/student", title: "mobile-student-home", group: "Mobile", figmaId: "65:5044" },
  { id: "SH-mobile-course", role: "mobile", path: "/m/student/courses", title: "mobile-course", group: "Mobile", figmaId: "65:5112" },
  { id: "MB-10", role: "mobile", path: "/m/student/documents", title: "mb-10-mobile-documents", group: "Mobile", figmaId: "66:7538" },
  { id: "MB-08", role: "mobile", path: "/m/student/fees", title: "mb-08-mobile-fees", group: "Mobile", figmaId: "66:7390" },
  { id: "MB-04", role: "mobile", path: "/m/student/grades", title: "mb-04-mobile-grades", group: "Mobile", figmaId: "66:7170" },
  { id: "MB-09", role: "mobile", path: "/m/student/library", title: "mb-09-mobile-library", group: "Mobile", figmaId: "66:7460" },
  { id: "MB-07", role: "mobile", path: "/m/student/profile", title: "mb-07-mobile-profile", group: "Mobile", figmaId: "66:7327" },
  { id: "SH-02", role: "shared", path: "/mfa", title: "sh-02-mfa", group: "Shared", figmaId: "17:3179" },
  { id: "SH-15", role: "shared", path: "/offline", title: "sh-15-error-5xx", group: "Shared", figmaId: "66:436" },
  { id: "SH-10", role: "shared", path: "/privacy", title: "SH-10-Privacy", group: "Shared", figmaId: "17:13640" },
  { id: "SH-03", role: "shared", path: "/reset", title: "SH-03-Reset-Password", group: "Shared", figmaId: "17:13395" },
  { id: "SH-04", role: "shared", path: "/role-select", title: "sh-04-role-selection", group: "Shared", figmaId: "17:3221" },
  { id: "MAP", role: "shared", path: "/screens", title: "All screens map", group: "Shared" },
  { id: "CP-08", role: "shared", path: "/shared/f/cp-08-inspection-pack-builder", title: "cp-08-inspection-pack-builder", group: "Shared", figmaId: "102:1734" },
  { id: "ST-01", role: "student", path: "/student", title: "st-01-student-dashboard", group: "Student", figmaId: "17:60" },
  { id: "ST-15", role: "student", path: "/student/advising", title: "st-15-advising", group: "Student", figmaId: "17:4455" },
  { id: "ST-ALL", role: "student", path: "/student/all", title: "All student screens", group: "Student" },
  { id: "ST-ANN", role: "student", path: "/student/announcements", title: "Announcements", group: "Student" },
  { id: "ST-14", role: "student", path: "/student/ask", title: "st-14-ai-tutor", group: "Student", figmaId: "17:4353" },
  { id: "ST-ASM", role: "student", path: "/student/assessments", title: "Assessments", group: "Student" },
  { id: "ST-ASN", role: "student", path: "/student/assignments", title: "Assignments (live)", group: "Student" },
  { id: "ST-08", role: "student", path: "/student/attendance", title: "st-08-attendance", group: "Student", figmaId: "17:3833" },
  { id: "ST-09", role: "student", path: "/student/calendar", title: "st-09-schedule", group: "Student", figmaId: "17:3940" },
  { id: "ST-CONT", role: "student", path: "/student/continue", title: "Continue learning", group: "Student" },
  { id: "ST-02", role: "student", path: "/student/courses", title: "st-02-my-courses", group: "Student", figmaId: "17:3341" },
  { id: "ST-03", role: "student", path: "/student/courses/demo", title: "st-03-course-detail", group: "Student", figmaId: "17:581" },
  { id: "ST-DOC", role: "student", path: "/student/documents", title: "Documents", group: "Student" },
  { id: "ST-04", role: "student", path: "/student/f/st-04-assignments", title: "st-04-assignments", group: "Student", figmaId: "17:3449" },
  { id: "ST-05", role: "student", path: "/student/f/st-05-assignment-detail", title: "st-05-assignment-detail", group: "Student", figmaId: "17:3548" },
  { id: "ST-06", role: "student", path: "/student/f/st-06-assessments", title: "st-06-assessments", group: "Student", figmaId: "17:3660" },
  { id: "ST-11", role: "student", path: "/student/f/st-11-lecture-detail", title: "st-11-lecture-detail", group: "Student", figmaId: "17:3051" },
  { id: "ST-13", role: "student", path: "/student/f/st-13-lab-detail", title: "st-13-lab-detail", group: "Student", figmaId: "17:4234" },
  { id: "ST-16", role: "student", path: "/student/f/st-16-services", title: "st-16-services", group: "Student", figmaId: "17:4571" },
  { id: "ST-17", role: "student", path: "/student/f/st-17-practicum", title: "st-17-practicum", group: "Student", figmaId: "17:4682" },
  { id: "ST-19", role: "student", path: "/student/f/st-19-credentials", title: "st-19-credentials", group: "Student", figmaId: "17:4895" },
  { id: "ST-20", role: "student", path: "/student/f/st-20-career", title: "st-20-career", group: "Student", figmaId: "17:5009" },
  { id: "ST-18", role: "student", path: "/student/fees", title: "st-18-finance", group: "Student", figmaId: "17:4798" },
  { id: "ST-07", role: "student", path: "/student/grades", title: "st-07-grades", group: "Student", figmaId: "17:3748" },
  { id: "ST-HLD", role: "student", path: "/student/holds", title: "Holds", group: "Student" },
  { id: "ST-12", role: "student", path: "/student/labs", title: "st-12-labs", group: "Student", figmaId: "17:4131" },
  { id: "ST-10", role: "student", path: "/student/lectures", title: "st-10-lectures", group: "Student", figmaId: "17:4046" },
  { id: "ST-22", role: "student", path: "/student/library", title: "st-22-resources", group: "Student", figmaId: "17:5245" },
  { id: "ST-21", role: "student", path: "/student/messages", title: "st-21-messages", group: "Student", figmaId: "17:5133" },
  { id: "ST-MOD", role: "student", path: "/student/modules", title: "Modules", group: "Student" },
  { id: "ST-NTF", role: "student", path: "/student/notifications", title: "Notifications", group: "Student" },
  { id: "ST-PRF", role: "student", path: "/student/profile", title: "Profile", group: "Student" },
  { id: "ST-SRC", role: "student", path: "/student/search", title: "Search", group: "Student" },
  { id: "ST-SUC", role: "student", path: "/student/success", title: "Success", group: "Student" },
  { id: "AD-AUDIT", role: "admin", path: "/admin/audit", title: "Audit log", group: "Admin" },
  { id: "AD-CORR", role: "admin", path: "/admin/corrections", title: "Corrections", group: "Admin" },
  { id: "AD-HELP", role: "admin", path: "/admin/help", title: "Help desk", group: "Admin" },
  { id: "AD-JOBS", role: "admin", path: "/admin/jobs", title: "Jobs", group: "Admin" },
  { id: "AD-OPS", role: "admin", path: "/admin/operations", title: "Operations", group: "Admin" },
  { id: "AD-SET", role: "admin", path: "/admin/settings", title: "Settings", group: "Admin" },
];

export function screensForGroup(group: string) {
  return ALL_SCREENS.filter((s) => s.group === group);
}

export const FIGMA_COUNTS = {
  adminUnique: 137,
  teacherUnique: 83,
  studentUnique: 34,
  authUnique: 49,
  componentsUnique: 14,
  catalogPaths: 312,
} as const;
