export type OnlineAdminScreen = {
  slug: string;
  label: string;
  group: "Learning operations" | "Academic delivery" | "Governance" | "Configuration";
  description: string;
  fields: string[];
  actions: string[];
  workflow: string;
  safeguard: string;
  columns: string[];
  rows: string[][];
};

/**
 * Admin-facing coverage catalogue for the HCC Online integration. These labels intentionally
 * stay explicit: the page doubles as a UI and a reviewable inventory of the requested data.
 */
export const ONLINE_ADMIN_SCREENS: OnlineAdminScreen[] = [
  {
    slug: "overview",
    label: "Overview",
    group: "Learning operations",
    description: "Institution-wide online learning health without double-counting SIS records or finance.",
    fields: ["Online-enabled students", "Active learning enrolments", "Published learning programs", "Recent enrolments", "Pending assignment grading", "Integrity cases", "Last successful data refresh", "Collected payments", "Outstanding fees", "Refunds"],
    actions: ["View Online Students", "View Learning Progress", "Pending Grading", "Open Integrity Queue", "Resend Welcome"],
    workflow: "Dashboard card → linked student, enrolment, course or report record.",
    safeguard: "Student, enrolment and payment counts remain separate; online revenue is not added to the SIS ledger total.",
    columns: ["Activity", "Student / item", "State", "Last update"],
    rows: [["New enrolment", "Maya Singh · Pharmacy Assistant", "Access active", "8 min ago"], ["AI draft submitted", "Office Administration · v3", "Faculty review", "24 min ago"], ["Integrity signal", "Attempt QA-2048", "Review required", "42 min ago"]],
  },
  {
    slug: "applications",
    label: "Applications & pending review",
    group: "Learning operations",
    description: "Online applications enter the existing admission decision and document workflow.",
    fields: ["Application ID", "Student ID / reference", "Application source", "Applicant identity", "Program", "Term", "Campus", "Cohort", "Document references", "Review status", "Reviewer", "Review date", "Learning access status"],
    actions: ["View Online Application", "View Documents", "Review", "Approve", "View Learning Access Status"],
    workflow: "Online application → staff review → admission decision → document issuance → eligible learning access.",
    safeguard: "Admission approval and learning access are separate decisions; approval is never performed independently in two systems.",
    columns: ["Application", "Applicant", "Program / cohort", "Review", "Access"],
    rows: [["APP-OL-1048", "Maya Singh", "Pharmacy Assistant · Fall 2026 A", "In review", "Pending"], ["APP-OL-1044", "Ethan Clark", "Office Administration · Fall 2026", "Documents required", "Blocked"]],
  },
  {
    slug: "enrolments",
    label: "Online students & enrolments",
    group: "Learning operations",
    description: "Enrolment-level learning access, progress, attempts and sync state linked to one canonical student.",
    fields: ["Canonical Student ID", "Online User ID", "Learning Enrolment ID", "Email", "Full name", "Phone", "Country", "Optional student ID", "Address", "Date of birth", "Gender", "Residency", "Campus", "Intake", "Admission term", "Language of instruction", "Payment mode", "Program / Course", "Cohort", "Access state", "Progress", "Learning completion state", "Official student status", "Archived / Trash interface state", "Last activity", "Study minutes", "Assignment status", "Quiz summary", "Integrity status", "Last sync", "Account status", "Admin notes", "LOA / COL log"],
    actions: ["Open Learning Record", "View Attendance", "View Attempts", "Enrol in Another Program", "Send Password Setup / Reset", "Retry Sync", "Export CSV"],
    workflow: "Existing/new student → official enrolment → fee/award reference → learning-access request → welcome notification.",
    safeguard: "Email is not the permanent identity key. Multiple program enrolments reuse the same person and account.",
    columns: ["Student", "Enrolment", "Progress", "Access", "Last activity"],
    rows: [["HCC-24018 · Maya Singh", "Pharmacy Assistant · 2026-FA-A", "64%", "Active", "Today, 10:42"], ["HCC-23902 · Liam Martin", "Office Administration · 2026-FA", "18%", "Active", "Yesterday"]],
  },
  {
    slug: "users",
    label: "Instructors & online users",
    group: "Learning operations",
    description: "Canonical identities, onboarding and scoped online roles for students, instructors, SMEs and admins.",
    fields: ["Canonical User ID", "Online User ID", "Full name", "Email", "Employee ID", "Role mapping: Student", "Role mapping: Instructor", "Role mapping: SME", "Role mapping: Admin", "Campus scope", "Assigned programs / courses", "Account state", "Password-setup state", "Member since", "Two-factor state", "Active sessions"],
    actions: ["Add / Link Instructor", "Assign Program / Course", "Send Setup Link", "Reset Password", "Deactivate", "View Online Permissions", "CSV Import", "Start Audited Support Session"],
    workflow: "Canonical user → online identity link → role and scope → secure setup notification.",
    safeguard: "Online Admin never implies SIS Super Admin. Support sessions cannot submit quizzes, payments or credential decisions.",
    columns: ["User", "Online role", "Scope", "Account", "Setup"],
    rows: [["EMP-018 · Olivia Brown", "Instructor", "Pharmacy Assistant", "Active", "Complete"], ["EMP-031 · Noah Wilson", "SME", "Office Administration", "Active", "Link sent"]],
  },
  {
    slug: "catalogue",
    label: "Programs & catalogue mapping",
    group: "Academic delivery",
    description: "Map each online item to the correct SIS program, course, workshop or entry test before publication.",
    fields: ["Online item ID", "Online title", "Academic Entity Type", "Linked Program ID", "Linked Course ID", "Curriculum version", "Delivery platform", "Publication status", "Sync status", "Domestic tuition", "International tuition", "Instructor assignment"],
    actions: ["Create Course", "Create with AI", "Link Existing Record", "Create Mapping", "Review Mapping", "Sync Metadata", "Open Online Item", "Edit Details", "Edit Content", "Preview"],
    workflow: "Academic item approved → mapping reviewed → content approved → online catalogue publication.",
    safeguard: "A title alone cannot decide whether an item is a Program, Course, Workshop or Entry Test.",
    columns: ["Online item", "Academic mapping", "Version", "Publication", "Sync"],
    rows: [["OL-OA-001 · Office Administration Diploma", "Program · PRG-OA", "v3", "Published", "Healthy"], ["OL-PA-001 · Pharmacy Assistant", "Program · PRG-PA", "v2", "Published", "Healthy"], ["OL-RS-EL · Red Seal Electrician", "Course · CRS-RSE", "Draft v1", "Faculty review", "Not synced"]],
  },
  {
    slug: "schedules",
    label: "Program schedules & cohorts",
    group: "Academic delivery",
    description: "Publish approved intake and cohort dates from Master Scheduling to the online catalogue.",
    fields: ["Program ID", "Cohort ID", "Admission Term ID", "Campus ID", "Start date", "End date", "Timezone", "Credential category", "Delivery mode", "Online availability"],
    actions: ["Set Dates", "Add Cohort Date", "Save Schedule", "Publish Intake Online", "Sync Cohort", "View Online Applications"],
    workflow: "Approved SIS intake/cohort → online dates → applicant selection → same cohort reference on enrolment.",
    safeguard: "Admission Term, Cohort, Campus, Delivery Mode and content-publication date remain separate values.",
    columns: ["Program / cohort", "Term", "Campus / mode", "Dates", "Online"],
    rows: [["Pharmacy Assistant · 2026-FA-A", "Fall 2026", "Surrey · Online", "Sep 14 – Dec 18", "Published"], ["Office Administration · 2027-WI-A", "Winter 2027", "Vancouver · Online", "Jan 11 – Apr 30", "Ready to publish"]],
  },
  {
    slug: "content",
    label: "Curriculum & AI drafts",
    group: "Academic delivery",
    description: "Manual and AI-assisted chapter, lesson, resource, quiz and assignment authoring with approval gates.",
    fields: ["Course code", "Credits", "Required hours", "Prerequisites", "Grading scheme", "Program association", "Linked online content ID", "Curriculum version", "Chapter / lesson structure", "Content resources", "Assignments", "Quizzes", "Learning activity", "Assigned instructor", "Delivery platform", "Publish / sync status", "AI source outline", "AI generation notes"],
    actions: ["Edit Online Content", "Generate AI Draft", "Add Chapter", "Add Lesson", "Preview as Learner", "Submit for Review", "Approve Version", "Publish Approved Version"],
    workflow: "Manual/AI draft → faculty or SME review → approved version → publish → assigned enrolments use that version.",
    safeguard: "AI never publishes directly; active cohorts and historical attempts are not silently moved to a new version.",
    columns: ["Course", "Content", "Owner", "Version", "Review"],
    rows: [["OA-101 · Office Procedures", "12 chapters · 74 activities", "Olivia Brown", "v3", "Published"], ["RSE-100 · Exam Foundations", "6 chapters · 38 activities", "Noah Wilson", "Draft v1", "SME review"]],
  },
  {
    slug: "grading",
    label: "Assignments, quizzes & grades",
    group: "Academic delivery",
    description: "Raw online attempts flow through instructor review and final-grade approval before transcripts.",
    fields: ["Student", "Academic enrolment ID", "Learning enrolment ID", "Course", "Assessment", "Attempt number", "Submission date", "Score", "Maximum marks", "Grading state", "Reviewer", "Feedback reference", "Integrity flag", "Assessment weight", "Grading scheme", "Final mark state"],
    actions: ["View Submission", "Grade", "Request Recheck", "Submit Final Marks", "Approve Final Marks", "View Attempts"],
    workflow: "Submission / quiz attempt → reviewed assessment result → final-grade approval → transcript.",
    safeguard: "An attempt score never overwrites an official transcript mark without attempt-selection, weighting and approval rules.",
    columns: ["Student / assessment", "Attempt", "Score", "Grading", "Integrity"],
    rows: [["Maya Singh · Chapter 4 assessment", "2", "82 / 100", "Reviewed", "Clear"], ["Liam Martin · Records quiz", "1", "74 / 100", "Awaiting review", "Flagged"]],
  },
  {
    slug: "attendance",
    label: "Online attendance",
    group: "Academic delivery",
    description: "Study activity and institution-approved academic attendance remain visible as separate values.",
    fields: ["Student", "Enrolment", "Course / Program", "Activity date", "Timezone", "Study minutes", "Study-minutes chart", "Attendance calendar", "Activity source", "Calculated online presence", "Approved academic attendance", "Correction reason", "Classroom attendance", "Leave / non-teaching day"],
    actions: ["View Activity", "Review Attendance", "Correct with Reason", "Download Excel", "Export Attendance"],
    workflow: "Learning activity → platform presence calculation → institutional review → approved attendance report.",
    safeguard: "The platform 10-minute rule is not automatically the academic standard; hybrid activity is not double-counted.",
    columns: ["Student", "Date / timezone", "Study", "Online presence", "Approved"],
    rows: [["Maya Singh", "Oct 7 · America/Vancouver", "46 min", "Present", "Present"], ["Liam Martin", "Oct 7 · America/Vancouver", "8 min", "Below threshold", "Pending review"]],
  },
  {
    slug: "english-test",
    label: "HCC English Test",
    group: "Academic delivery",
    description: "Registrations, sessions, attempts and reviewed results linked to admission requirements.",
    fields: ["Applicant reference", "Student ID (optional)", "Identity", "Contact", "Communication preference", "Test registration ID", "Session ID", "Attempt", "Test state", "Reviewed result", "Admission requirement", "Pass threshold rule"],
    actions: ["View Test Profile", "Open Session", "Review Result", "Link Student", "Apply Result to Requirement"],
    workflow: "Applicant registration → test session → attempt → review → approved result → admission requirement update.",
    safeguard: "A test applicant is not made an Active Student, and a score does not approve admission unless a configured rule allows it.",
    columns: ["Applicant", "Registration / session", "Attempt", "State", "Requirement"],
    rows: [["Ava Chen", "HET-1042 · SES-88", "1", "Awaiting review", "English proficiency"], ["Daniel Kim", "HET-1038 · SES-86", "2", "Completed", "Satisfied"]],
  },
  {
    slug: "requests",
    label: "Online requests",
    group: "Governance",
    description: "Online-originated requests enter the existing common review queue with source references.",
    fields: ["Request ID", "Source = Online Portal", "Original request reference", "Request type", "Student", "Affected enrolment", "Submitted date", "Review status", "Reviewer", "Decision", "Learning-access effect", "Notification state"],
    actions: ["Open Request", "Confirm Request Type", "Assign Reviewer", "Approve", "Decline", "View Enrolment"],
    workflow: "Online request → common queue → authorized decision → scoped record/access update → notification.",
    safeguard: "Leave or withdrawal affects only the selected enrolment, never unrelated programs.",
    columns: ["Request", "Student / enrolment", "Type", "Review", "Access effect"],
    rows: [["REQ-OL-188", "Maya Singh · PA-2026", "Profile change", "Assigned", "None"], ["REQ-OL-184", "Liam Martin · OA-2026", "Withdrawal", "Decision pending", "Not applied"]],
  },
  {
    slug: "integrity",
    label: "Academic integrity",
    group: "Governance",
    description: "Evidence-led, enrolment-scoped integrity review with auditable human decisions.",
    fields: ["Case ID", "Student", "Enrolment", "Course / Assessment", "Quiz flags", "Tab switches", "Window blurs", "Copy attempts", "Focused time", "Expected time", "Evidence references", "Risk", "Review status", "Assigned reviewer", "Decision", "Reason", "Credential impact", "Audit history"],
    actions: ["View Evidence", "Assign Reviewer", "Clear – no misconduct", "Issue Warning", "Revoke & Reset", "View Decision History", "Export Dossier"],
    workflow: "Detection signal → evidence review → authorized decision → scoped hold/attempt/credential effect.",
    safeguard: "A flag is not misconduct. Revoke & Reset requires record, reason and confirmation while preserving original evidence and attempts.",
    columns: ["Case", "Student / assessment", "Risk", "Evidence", "Review"],
    rows: [["INT-2048", "Liam Martin · Records quiz", "Medium", "3 tab switches · 2 blurs", "Unassigned"], ["INT-2039", "Maya Singh · Chapter 3", "Low", "Timing variance", "Cleared"]],
  },
  {
    slug: "finance",
    label: "Pricing, payments & access",
    group: "Governance",
    description: "Approved SIS fee rules drive online display prices and enrolment access eligibility.",
    fields: ["Academic Program / Course", "Rate Category", "Fee / Ledger Type", "Term / Cohort", "Currency", "Price Version", "Promotion", "Domestic tuition", "International tuition", "Charge level (program/course)", "Invoice ID", "Payment ID", "Allocation reference", "Award / bursary", "Payment plan", "Access eligibility", "Online order reference", "Refund scope"],
    actions: ["View Fee Breakdown", "Create / View Invoice", "View Payment", "Apply Approved Award", "Review Access Eligibility", "Reconcile Order"],
    workflow: "Enrolment → fee assessment → invoice → payment/award/arrangement → access eligibility → online access.",
    safeguard: "Payment callbacks are idempotent; refunds, withdrawals and access changes are separate controlled operations.",
    columns: ["Enrolment", "Fee / price version", "Financial state", "Access", "Reconciliation"],
    rows: [["PA-2026 · Maya Singh", "Domestic · CAD 7,200 · v2", "Paid", "Eligible", "Matched"], ["OA-2026 · Liam Martin", "International · CAD 11,750 · v3", "Instalment plan", "Eligible by policy", "Matched"]],
  },
  {
    slug: "reports",
    label: "Online learning reports",
    group: "Governance",
    description: "Operational and academic reports with explicit units, freshness and reusable filters.",
    fields: ["Online Admissions", "Enrolment-to-Access Status", "Learning Progress", "Assignment Grading", "Quiz Attempts", "Online Attendance", "Integrity Cases", "English Test Results", "Online Payment Reconciliation", "Credential Status", "Campus", "Program", "Course", "Cohort", "Term", "Instructor", "Student", "Date range", "Delivery platform", "Status", "Last updated at"],
    actions: ["Run Report", "Export", "Schedule", "Open Student / Enrolment"],
    workflow: "Select report and filters → run against canonical references → show freshness → export or schedule.",
    safeguard: "Student, program enrolment, course enrolment and attempt counts are never presented as the same metric.",
    columns: ["Report", "Primary unit", "Last run", "Freshness", "Schedule"],
    rows: [["Learning Progress", "Course enrolment", "Today, 11:10", "Synced 5 min ago", "Every Monday"], ["Payment Reconciliation", "Invoice / order", "Today, 09:00", "Synced 12 min ago", "Daily"]],
  },
  {
    slug: "branding",
    label: "Online branding",
    group: "Configuration",
    description: "Approved brand and campus identity shared with the learning portal, emails and future credentials.",
    fields: ["Brand ID", "Institution display name", "Tagline", "Logo asset", "Online domain", "Applicable campuses", "Brand version", "Last sync", "Welcome email preview"],
    actions: ["Preview Online Branding", "Sync Branding", "Send Test Welcome Email", "View Version History"],
    workflow: "Approved brand version → scoped campuses → portal/email sync → preview and audit.",
    safeguard: "Campus and Delivery Mode remain distinct; already issued documents are not rewritten without version history.",
    columns: ["Brand", "Domain", "Campuses", "Version", "Sync"],
    rows: [["HCC · Heritage Community College", "hccbconline.com", "Vancouver, Surrey", "v6", "Healthy"]],
  },
  {
    slug: "workshops",
    label: "Online workshops",
    group: "Academic delivery",
    description: "Existing Heritage workshops can link to online content without becoming program enrolments.",
    fields: ["Workshop ID", "Linked online content", "User / Enrolment ID", "Instructor", "Start / End dates", "Capacity", "Fee reference", "Attendance source", "Completion state", "Delivery mode"],
    actions: ["Link Online Content", "Open Workshop Learning", "View Online Attendance", "Review Completion"],
    workflow: "Workshop → content link → approval/financial eligibility → access → attendance/result → completion.",
    safeguard: "Workshop completion never graduates a student from an academic program.",
    columns: ["Workshop", "Online content", "Instructor / dates", "Capacity", "Completion"],
    rows: [["WS-204 · Workplace Safety", "OL-WS-44", "Olivia Brown · Nov 8", "18 / 24", "In progress"]],
  },
  {
    slug: "integration",
    label: "Integration centre",
    group: "Configuration",
    description: "Connection, mapping, sync failures and reconciliation for authorized technical administrators.",
    fields: ["Source system", "Entity type", "Source ID", "Target ID", "Canonical User ID ↔ Online User ID", "Student ID ↔ Online Student/Profile ID", "Application ID ↔ Source application reference", "Program/Course/Workshop/Test ID ↔ Online item ID", "Schedule/Cohort ID ↔ Online Cohort ID", "Academic Enrolment ID ↔ Learning Enrolment ID", "Course/Assessment ID ↔ Online assessment and attempt IDs", "Invoice/Payment/Award ID ↔ Online order/payment reference", "Official credential ID ↔ Online credential reference", "Event ID", "Event type", "Event version", "Last successful sync", "Latest version", "Sync status", "Error reason", "Retry count", "Conflict state", "Connection state"],
    actions: ["Test Connection", "Validate Mapping", "Retry Failed", "Compare Records", "Pause Sync", "Resume Sync", "Open Sync Log", "Reconcile"],
    workflow: "Source event → idempotency/version check → mapping → target update or review queue → sync history.",
    safeguard: "Retries do not duplicate records; older events do not overwrite newer state; conflicts require review.",
    columns: ["Entity / mapping", "Latest event", "Version", "Status", "Retry"],
    rows: [["Enrolment · ENR-1042 ↔ LEN-884", "access.updated", "18", "Synced", "0"], ["Course · CRS-RSE ↔ OL-RS-EL", "content.versioned", "3", "Conflict review", "2"]],
  },
  {
    slug: "documents",
    label: "Documents & credentials",
    group: "Configuration",
    description: "One authorized issuance and notification history for LOA, COL, welcome messages and credentials.",
    fields: ["Document ID", "Student", "Enrolment", "Document type", "Template version", "Issue date", "Current status", "File reference", "Issuing actor", "Credential ID", "Online credential reference", "Welcome notification ID", "Resend history"],
    actions: ["Open Document", "Issue Authorized Document", "Resend Welcome", "View Credential", "View History"],
    workflow: "Authorized decision → one document/credential issuance → one notification record → linked online reference.",
    safeguard: "Resend Welcome only resends communication; it never creates another admission, enrolment or invoice. COL remains an unexpanded label.",
    columns: ["Document / credential", "Student / enrolment", "Version", "Status", "Issued"],
    rows: [["LOA-2026-188", "Maya Singh · PA-2026", "Template v4", "Issued", "Sep 2"], ["COL-2026-044", "Liam Martin · OA-2026", "Template v2", "Active", "Sep 6"]],
  },
  {
    slug: "security",
    label: "Security & data sharing",
    group: "Configuration",
    description: "Shared identity with least-privilege data exchange and independent authorization checks.",
    fields: ["Canonical identity", "Online identity", "Display name", "Required contact", "Role", "Assigned enrolments", "Access state", "Shared field policy", "Two-factor policy", "Session policy", "Password reset state", "Deactivation effect", "Audit actor / reason"],
    actions: ["Review Shared Fields", "Manage Account Security", "View Linked Learning Account", "View Active Sessions", "Revoke Session", "Audit Support Access"],
    workflow: "Identity authentication → system-specific authorization → minimum permitted data → audited session.",
    safeguard: "SIN, passport scans, sensitive admission data and detailed fee notes are not replicated to the learning platform by default.",
    columns: ["Policy", "Applies to", "State", "Last review", "Owner"],
    rows: [["Minimum learner profile", "Student + enrolments", "Enforced", "Sep 28", "Privacy Officer"], ["Online admin scope", "Admin roles", "Enforced", "Oct 1", "Security Admin"]],
  },
  {
    slug: "profile",
    label: "My online account",
    group: "Configuration",
    description: "Admin account details, linked learning identity and security controls without replacing the existing Heritage profile.",
    fields: ["Account name", "Email", "Online role", "Member since", "Canonical User ID", "Online User ID", "Linked learning account", "Password state", "Two-factor authentication", "Active sessions", "Account deactivation effect"],
    actions: ["Manage Account Security", "View Linked Learning Account", "View Active Sessions", "Reset Password", "Enable Two-Factor Authentication"],
    workflow: "Canonical admin identity → linked online account → shared security policy → system-specific authorization.",
    safeguard: "The small online account view does not replace Heritage biography, availability, schedule or compensation sections.",
    columns: ["Account", "Online role", "Linked identity", "Two-factor", "Sessions"],
    rows: [["Alex Morgan · alex@heritagecollege.ca", "Online Admin", "USR-001 ↔ OLU-818", "Enabled", "2 active"]],
  },
];

export const ONLINE_ADMIN_GROUPS = ["Learning operations", "Academic delivery", "Governance", "Configuration"] as const;

export function onlineAdminScreen(slug: string) {
  return ONLINE_ADMIN_SCREENS.find((screen) => screen.slug === slug);
}
